import type { DailyQuestion } from "@/types/daily";
import { DAILY_SCENARIO_QUESTION_BANK } from "@/content/daily/scenario-templates";

export const LEGACY_DAILY_QUESTION_BANK: DailyQuestion[] = [
  {
    id: "math-fruit-share-1",
    themeId: "math",
    title: "8 块水果怎么分",
    progressionStageId: "foundation-observe",
    sceneSetup: "林老师抱着一盘切好的水果，三个小朋友已经围到桌边了。",
    sceneDetail: "林老师压低声音说：我一分就怕有人皱眉，你帮我想个不容易吵起来的办法。",
    hook: "林老师想请你当今天的分水果队长。",
    mainQuestion: "3 个小朋友来分这 8 块水果，你会怎么分，大家比较容易点头？",
    firstFollowUp: "你为什么会想这样分呀？",
    twistFollowUp: "要是又来了第 4 个小朋友，你会怎么改？",
    suggestedInput: "voice",
    goalId: "math-thinking",
    subGoalId: "quantity-comparison",
    coachFocus: "引导孩子比较数量、解释差值，并发现平均分不整时也能讨论更公平的办法。",
  },
  {
    id: "math-shop-change-1",
    themeId: "math",
    title: "买两样东西要带多少钱",
    progressionStageId: "foundation-observe",
    sceneSetup: "林老师站在小商店门口，口袋里只有几枚硬币在叮当响。",
    sceneDetail: "林老师把面包和牛奶指给你看，小声问：我不想带多了，也不想到了柜台才发现不够。",
    hook: "林老师想先算好口袋里的钱。",
    mainQuestion: "一个面包 6 元，一盒牛奶 4 元。林老师最少带多少钱才一定够？",
    firstFollowUp: "你刚才是怎么一下子想到 10 的？",
    twistFollowUp: "要是林老师还想买 1 元的贴纸，你会先算哪一步？",
    suggestedInput: "voice",
    goalId: "math-thinking",
    subGoalId: "quantity-comparison",
    coachFocus: "鼓励孩子把总数想清楚，再说出自己是怎么合起来的。",
  },
  {
    id: "math-shortcut-1",
    themeId: "math",
    title: "哪种数法更省劲",
    progressionStageId: "strategy-pattern",
    sceneSetup: "地上散着 12 颗亮亮的扣子，林老师已经蹲下来准备开始数了。",
    sceneDetail: "林老师抬头看看你：我想找一种又快又不容易数错的办法。",
    hook: "林老师想学一种更省劲的数法。",
    mainQuestion: "地上有 12 颗扣子，你会一颗一颗数，还是 2 颗 2 颗数？",
    firstFollowUp: "你觉得哪种更省劲？为什么？",
    twistFollowUp: "要是变成 11 颗，这个办法还一样顺手吗？",
    suggestedInput: "choice",
    goalId: "math-thinking",
    subGoalId: "strategy-planning",
    coachFocus: "引导孩子比较不同策略的效率，并注意奇偶变化带来的影响。",
  },
  {
    id: "math-many-ways-1",
    themeId: "math",
    title: "7 可以拆成几种",
    progressionStageId: "foundation-observe",
    sceneSetup: "林老师把 7 块小积木推到桌子中间，左右各留了一小块空位。",
    sceneDetail: "林老师笑着说：我想把 7 拆开玩玩，可不想只想到一种。",
    hook: "数字积木今天想玩“拆一拆”的游戏。",
    mainQuestion: "7 可以拆成两个数，你先想到哪一组？",
    firstFollowUp: "还有别的拆法吗？再想一个给林老师听。",
    twistFollowUp: "要是两边要一样多，7 办得到吗？",
    suggestedInput: "text",
    goalId: "math-thinking",
    subGoalId: "quantity-comparison",
    coachFocus: "鼓励孩子生成多种组合，再比较其中哪些更对称、更特别。",
  },
  {
    id: "math-stairs-1",
    themeId: "math",
    title: "上 10 级台阶怎么走",
    progressionStageId: "strategy-pattern",
    sceneSetup: "林老师站在 10 级台阶下面，已经把脚尖点到了第一格。",
    sceneDetail: "林老师边比划边说：我想快一点到上面，但也不想走着走着乱掉。",
    hook: "林老师站在楼梯口，想试试更聪明的走法。",
    mainQuestion: "要走上 10 级台阶，你会每次走 1 级，还是有时候走 2 级？",
    firstFollowUp: "你为什么觉得这样走更好？",
    twistFollowUp: "要是最后一级特别高，你会不会改办法？",
    suggestedInput: "voice",
    goalId: "math-thinking",
    subGoalId: "strategy-planning",
    coachFocus: "让孩子比较不同走法的节奏与结果，练习先想后做。",
  },
  {
    id: "math-seat-rows-1",
    themeId: "math",
    title: "12 个座位怎么排",
    progressionStageId: "foundation-observe",
    sceneSetup: "教室角落里堆着 12 把小椅子，林老师正把它们一把一把拖出来。",
    sceneDetail: "林老师回头问你：我想摆得整齐一点，还得留地方让大家走来走去。",
    hook: "林老师想帮教室把小椅子摆得又整齐又好走。",
    mainQuestion: "12 把小椅子，排成 3 排还是 4 排，你会先怎么想？",
    firstFollowUp: "你会不会先算一算每排有几把？",
    twistFollowUp: "要是中间还要留一条走路的空位，你会怎么摆？",
    suggestedInput: "voice",
    goalId: "math-thinking",
    subGoalId: "spatial-reasoning",
    coachFocus: "把数量关系和空间摆放连起来，让孩子看到“数”和“形”是一起想的。",
  },
  {
    id: "math-rule-sentence-1",
    themeId: "math",
    title: "把排法说成一句规则",
    progressionStageId: "rules-expression",
    sceneSetup: "林老师把一串彩珠排成红红蓝、红红蓝，盯着看了一会儿。",
    sceneDetail: "林老师轻轻敲了敲桌子：我好像看出来了，可我想把这个排法说成一句短短的话。",
    hook: "林老师想练习把看见的规律说成一句小规则。",
    mainQuestion: "如果你要用一句短短的话把这个排法告诉林老师，你会怎么说？",
    firstFollowUp: "你这句话里，最重要的是“重复”哪一小段？",
    twistFollowUp: "要是换成黄黄绿，你觉得还是同一家规则吗？",
    suggestedInput: "voice",
    goalId: "math-thinking",
    subGoalId: "pattern-recognition",
    coachFocus: "让孩子不只看见规律，还尝试把规律说成一条短规则。",
  },
  {
    id: "math-seat-rule-1",
    themeId: "math",
    title: "摆椅子先定什么规则",
    progressionStageId: "rules-expression",
    sceneSetup: "林老师要把 12 把小椅子摆进活动室里，可房间中间还要留出大家走路的地方。",
    sceneDetail: "林老师搬起一把椅子又放下：我觉得不能只是一把一把乱摆，得先定一个小规则。",
    hook: "林老师想先定一条摆椅子的小规则，再开始动手。",
    mainQuestion: "如果是你来摆，你会先定哪一条小规则，让椅子既整齐又好走？",
    firstFollowUp: "你为什么先定这条，不先定别的？",
    twistFollowUp: "要是门要从另一边打开，你这条规则还要不要改？",
    suggestedInput: "voice",
    goalId: "math-thinking",
    subGoalId: "spatial-reasoning",
    coachFocus: "让孩子从“直接做”过渡到“先定一条规则再做”。",
  },
  {
    id: "math-stair-rule-1",
    themeId: "math",
    title: "上楼梯怎么说成办法",
    progressionStageId: "rules-expression",
    sceneSetup: "林老师已经发现自己上楼时有时候一次跨两级，会更快一点。",
    sceneDetail: "林老师回头问你：我会这样走，可我还想把这个办法说清楚，教给别人。",
    hook: "林老师想把自己的走法变成一句别人也听得懂的小办法。",
    mainQuestion: "如果你要把这个走法教给另一个小朋友，你会怎么用一句话说清楚？",
    firstFollowUp: "你觉得这句办法里，哪一个词最关键？",
    twistFollowUp: "要是台阶忽然变高了，你这句办法还要不要改？",
    suggestedInput: "voice",
    goalId: "math-thinking",
    subGoalId: "strategy-planning",
    coachFocus: "让孩子把“我会做”推进成“我能把办法说清楚”。",
  },
  {
    id: "math-bridge-order-1",
    themeId: "math",
    title: "过小桥先让谁走",
    progressionStageId: "story-reasoning",
    sceneSetup: "林老师和几个小朋友站在一座窄窄的小桥前，一次只能过两个人。",
    sceneDetail: "桥那边已经在招手了，可桥面有点晃，林老师想先把顺序想好再动。",
    hook: "林老师想先定一个更稳的过桥顺序。",
    mainQuestion: "如果一次只能过两个人，你会先让谁走？为什么？",
    firstFollowUp: "你是在先想“快一点”，还是先想“稳一点”？",
    twistFollowUp: "要是其中一个人走得特别慢，你会不会换顺序？",
    suggestedInput: "voice",
    goalId: "math-thinking",
    subGoalId: "strategy-planning",
    coachFocus: "让孩子在连续决策里比较顺序、后果和稳妥程度。",
  },
  {
    id: "math-snack-transfer-1",
    themeId: "math",
    title: "换成大小不同的点心还怎么分",
    progressionStageId: "story-reasoning",
    sceneSetup: "昨天林老师分的是一样大的水果，今天桌上却是大饼干和小饼干混在一起。",
    sceneDetail: "林老师一边看一边犯嘀咕：昨天那个“先一人一点”的想法，今天还能不能继续用？",
    hook: "林老师想看看，昨天的分法换到今天还管不管用。",
    mainQuestion: "如果桌上有大饼干也有小饼干，你还会像昨天那样分吗？",
    firstFollowUp: "你觉得今天哪里和昨天一样，哪里已经不一样了？",
    twistFollowUp: "要是有人只想要小饼干，你原来的办法还要怎么改？",
    suggestedInput: "voice",
    goalId: "math-thinking",
    subGoalId: "quantity-comparison",
    coachFocus: "训练孩子把原来的分配思路迁移到条件变化的新情境里。",
  },
  {
    id: "math-map-route-1",
    themeId: "math",
    title: "送书路线要不要改",
    progressionStageId: "story-reasoning",
    sceneSetup: "林老师要把三摞书送到教室的三个角落，可教室中间忽然多出一张大桌子挡住了路。",
    sceneDetail: "林老师本来已经想好了一条顺路路线，现在又停下来重新看了一眼整个房间。",
    hook: "林老师想看看，原来的路线是不是还算最顺。",
    mainQuestion: "如果中间多了一张桌子，你会不会改送书路线？先怎么改？",
    firstFollowUp: "你改路线时先想的是少走路，还是少绕来绕去？",
    twistFollowUp: "要是桌子换到另一边，你的路线会不会又变？",
    suggestedInput: "voice",
    goalId: "math-thinking",
    subGoalId: "spatial-reasoning",
    coachFocus: "让孩子把空间路线和连续变化放在一起考虑，形成迁移式调整。",
  },
  {
    id: "pattern-scarf-1",
    themeId: "pattern",
    title: "围巾花纹下一格",
    adaptationLevel: 1,
    sceneSetup: "林老师把一条围巾摊在桌上，花纹一格一格排得很整齐。",
    sceneDetail: "林老师用手指点着最后一格说：我总觉得它下一下应该继续唱下去。",
    hook: "林老师看到一条围巾，花纹排得像在唱歌。",
    mainQuestion: "花纹是红红蓝、红红蓝，下一格最像什么？",
    firstFollowUp: "你是从哪里看出它在重复的？",
    twistFollowUp: "要是中间偷偷多了一个黄点，会发生什么？",
    suggestedInput: "choice",
    goalId: "observation-induction",
    subGoalId: "inductive-generalization",
    coachFocus: "让孩子先说出重复块，再讨论变化会不会打破原来的规则。",
  },
  {
    id: "pattern-steps-1",
    themeId: "pattern",
    title: "脚印在往哪边变",
    adaptationLevel: 1,
    sceneSetup: "沙地上留下了一串脚印，左一下、右一下，一直往前伸。",
    sceneDetail: "林老师蹲下来眯着眼睛看：它们像在排队，可又像在偷偷给我提示。",
    hook: "林老师在沙地上发现一串左一下、右一下的脚印。",
    mainQuestion: "脚印如果是左、右、左、右，接下来该是哪一只？",
    firstFollowUp: "你怎么知道不是另一只？",
    twistFollowUp: "要是后面突然连着出现两个右脚印，你会怎么解释？",
    suggestedInput: "voice",
    goalId: "observation-induction",
    subGoalId: "systematic-observation",
    coachFocus: "鼓励孩子明确说出排列顺序，并学习反驳错误可能。",
  },
  {
    id: "pattern-tower-1",
    themeId: "pattern",
    title: "积木塔每次怎么变",
    adaptationLevel: 2,
    sceneSetup: "林老师在地上摆了三座积木塔，一座比一座高。",
    sceneDetail: "林老师指着第三座说：我觉得后面这座应该也有自己的脾气，不会乱长。",
    hook: "林老师搭了一排积木塔，每一座都悄悄变高一点。",
    mainQuestion: "第一座 2 块，第二座 4 块，第三座 6 块。你猜下一座会怎样？",
    firstFollowUp: "你看到的是每次多几个，还是一下子变成几倍？",
    twistFollowUp: "要是第四座只有 7 块，你会不会觉得怪怪的？",
    suggestedInput: "voice",
    goalId: "observation-induction",
    subGoalId: "inductive-generalization",
    coachFocus: "让孩子区分“每次加多少”和“最后是多少”，避免只记结果不记规则。",
  },
  {
    id: "pattern-clap-1",
    themeId: "pattern",
    title: "拍手节奏少了什么",
    adaptationLevel: 2,
    sceneSetup: "林老师边走边拍手，拍拍停、拍拍停，可是中间突然卡了一下。",
    sceneDetail: "林老师笑着耸耸肩：我明明差一点就拍顺了，你帮我把那一下找回来。",
    hook: "林老师在练拍手节奏，可是中间漏了一下。",
    mainQuestion: "节奏是拍拍停、拍拍停，少掉的那一下应该是什么？",
    firstFollowUp: "你是从哪里听出它不一样的？",
    twistFollowUp: "要是改成拍停停，这个节奏会像什么？",
    suggestedInput: "choice",
    goalId: "observation-induction",
    subGoalId: "systematic-observation",
    coachFocus: "把声音规律说成看得见的节奏块，帮助孩子从听觉转成结构。",
  },
  {
    id: "pattern-window-1",
    themeId: "pattern",
    title: "窗户亮灯顺序",
    adaptationLevel: 3,
    sceneSetup: "晚上，大楼一格一格亮灯，像有人在空中悄悄打信号。",
    sceneDetail: "林老师抬头看了好久：我总觉得这些灯不是乱亮的，它们像在按自己的顺序眨眼。",
    hook: "林老师晚上看见大楼的窗户一格一格亮起来。",
    mainQuestion: "亮灯顺序是左、左、右、左、左、右，下一格最像会亮哪边？",
    firstFollowUp: "你觉得它更像两格一组，还是三格一组？",
    twistFollowUp: "要是最后一格改成中间那扇窗，这个规律还像原来的吗？",
    suggestedInput: "voice",
    goalId: "observation-induction",
    subGoalId: "inductive-generalization",
    coachFocus: "让孩子把重复块长度说出来，而不是只凭感觉报答案。",
  },
  {
    id: "pattern-turn-1",
    themeId: "pattern",
    title: "箭头在转圈吗",
    adaptationLevel: 3,
    sceneSetup: "桌上的小箭头卡片一张张摆开，看上去像在慢慢转弯。",
    sceneDetail: "林老师把最后一张卡住不放：我总觉得它下一下会继续转，可我想先听你怎么说。",
    hook: "林老师看到小箭头，好像每次都在转一点点。",
    mainQuestion: "箭头先朝上，再朝右，再朝下。你猜接下来会朝哪边？",
    firstFollowUp: "你觉得它是在转圈，还是在来回摆？",
    twistFollowUp: "要是它下一次又朝上，你会觉得它其实是什么规则？",
    suggestedInput: "voice",
    goalId: "observation-induction",
    subGoalId: "analogy-transfer",
    coachFocus: "把方向变化说成可迁移的规则，帮助孩子把图形变化和顺序规律联系起来。",
  },
  {
    id: "why-shadow-1",
    themeId: "why",
    title: "影子为什么跟着走",
    adaptationLevel: 1,
    sceneSetup: "太阳底下，林老师跑到哪，脚边那团黑影就跟到哪。",
    sceneDetail: "林老师停下来回头看了两次：我明明没拉着它，它怎么还是跟来了？",
    hook: "林老师今天在太阳下跑步，发现影子一直黏着自己。",
    mainQuestion: "你觉得影子为什么会跟着人走？",
    firstFollowUp: "要是太阳躲到云后面，影子会怎么样？",
    twistFollowUp: "要是晚上开手电筒，影子会不会又跑出来？",
    suggestedInput: "voice",
    goalId: "language-thinking",
    subGoalId: "explain-reasoning",
    coachFocus: "鼓励孩子先大胆猜，再用“因为”把自己的想法说完整。",
  },
  {
    id: "why-ice-1",
    themeId: "why",
    title: "冰为什么会变成水",
    adaptationLevel: 1,
    sceneSetup: "林老师把一小块冰放在桌上，刚开始它硬硬的、亮亮的。",
    sceneDetail: "过一会儿，桌上只剩下一小摊水，林老师皱了皱鼻子：它刚才明明不是这样的。",
    hook: "林老师把一小块冰放在桌上，过一会儿它就变样了。",
    mainQuestion: "你觉得冰为什么会慢慢变成水？",
    firstFollowUp: "你更觉得是桌子让它变的，还是空气让它变的？",
    twistFollowUp: "要是把它放回冰箱，它会怎么样？",
    suggestedInput: "voice",
    goalId: "language-thinking",
    subGoalId: "explain-reasoning",
    coachFocus: "让孩子从生活经验出发说原因，不追求标准答案，先鼓励解释。",
  },
  {
    id: "why-plant-1",
    themeId: "why",
    title: "植物为什么爱窗边",
    adaptationLevel: 2,
    sceneSetup: "窗边的小植物一整天都把叶子歪向亮亮的地方。",
    sceneDetail: "林老师把花盆轻轻转了一点：咦，它会不会过几天又悄悄转回去？",
    hook: "林老师发现窗边的小植物，总爱歪向亮亮的地方。",
    mainQuestion: "你觉得它为什么老想靠近窗边？",
    firstFollowUp: "要是把花盆转个方向，它会不会又慢慢转回来？",
    twistFollowUp: "要是窗帘一直拉着，它可能会怎样？",
    suggestedInput: "voice",
    goalId: "language-thinking",
    subGoalId: "describe-observation",
    coachFocus: "引导孩子先说看到的现象，再尝试解释原因。",
  },
  {
    id: "why-friend-1",
    themeId: "why",
    title: "朋友为什么突然不开心",
    adaptationLevel: 3,
    sceneSetup: "刚才还在笑的小朋友，忽然低下头，不说话了。",
    sceneDetail: "林老师也跟着安静下来：我不太想乱猜，可我又想知道是不是哪里不对了。",
    hook: "林老师看到一个小朋友刚刚还笑着，后来突然安静了。",
    mainQuestion: "你觉得一个人突然不开心，可能会是为什么？",
    firstFollowUp: "要是你不确定真正原因，你会先怎么做？",
    twistFollowUp: "要是换成你自己不开心，你希望别人怎么问你？",
    suggestedInput: "voice",
    goalId: "language-thinking",
    subGoalId: "explain-reasoning",
    coachFocus: "把解释和同理心放在一起，让孩子学会提出多种可能。",
  },
  {
    id: "why-rain-1",
    themeId: "why",
    title: "为什么下雨后会有小水坑",
    adaptationLevel: 2,
    sceneSetup: "雨刚停，地上这里一小摊、那里一小摊，亮亮地照着天光。",
    sceneDetail: "林老师踩了一脚水坑又退回来：为什么同一条路上，有的地方有水，有的地方却干干的？",
    hook: "林老师最喜欢踩水坑，可也老想知道水坑是怎么来的。",
    mainQuestion: "雨停以后，地上为什么会有一块一块的小水坑？",
    firstFollowUp: "为什么有的地方有水坑，有的地方却没有？",
    twistFollowUp: "要是第二天太阳很大，这些水坑会怎么样？",
    suggestedInput: "voice",
    goalId: "language-thinking",
    subGoalId: "describe-observation",
    coachFocus: "训练孩子把观察到的差异说出来，再往后推原因。",
  },
  {
    id: "why-socks-1",
    themeId: "why",
    title: "袜子为什么会只剩一只",
    adaptationLevel: 3,
    sceneSetup: "洗好的袜子一只只挂着，偏偏只少了一个搭档。",
    sceneDetail: "林老师把洗衣篮翻了一遍，还是没找到：它到底是自己躲起来了，还是被谁带走了？",
    hook: "林老师今天洗袜子，结果只找到一只。",
    mainQuestion: "你觉得袜子为什么有时候会只剩下一只？",
    firstFollowUp: "你能不能一下子想出两个不一样的原因？",
    twistFollowUp: "要是想让下次更容易找到，你会想什么办法？",
    suggestedInput: "voice",
    goalId: "language-thinking",
    subGoalId: "explain-reasoning",
    coachFocus: "鼓励孩子提出多种解释，再从解释走到办法。",
  },
  {
    id: "fairness-cookies-1",
    themeId: "fairness",
    title: "两块饼干算公平吗",
    adaptationLevel: 1,
    sceneSetup: "盘子里只剩下几块饼干，可每个人都已经把手伸过来了。",
    sceneDetail: "林老师边数边皱眉：如果每个人都拿一样多，是不是就一定没人心里别扭？",
    hook: "林老师今天要分点心，可每个人的肚子都不一样。",
    mainQuestion: "如果每个人都分到 2 块饼干，就一定算公平吗？",
    firstFollowUp: "你觉得“一样多”和“公平”是一回事吗？",
    twistFollowUp: "要是有一个人今天特别饿，你会怎么想？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "rule-creation",
    coachFocus: "让孩子开始区分“平均”与“合理”，不是只接受一个唯一答案。",
  },
  {
    id: "fairness-lineup-1",
    themeId: "fairness",
    title: "排队先后怎么定",
    adaptationLevel: 1,
    sceneSetup: "滑梯口已经排起小队，后面的人一边踮脚一边往前看。",
    sceneDetail: "林老师站在旁边有点发愁：我定规则的时候，最怕有人一下子觉得不服气。",
    hook: "林老师要带大家玩滑梯，可每个人都想先上。",
    mainQuestion: "排队时，你会定先来先玩，还是年纪小的先玩？",
    firstFollowUp: "你为什么会选这个规则？",
    twistFollowUp: "要是有个小朋友刚刚摔倒了，你的规则要不要变一下？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "rule-creation",
    coachFocus: "引导孩子设计规则、说出理由，并接受“规则也可能要改”。",
  },
  {
    id: "fairness-cleanup-1",
    themeId: "fairness",
    title: "收拾玩具怎么分工",
    adaptationLevel: 2,
    sceneSetup: "玩完积木后，地上铺得满满的，箱子却还空着。",
    sceneDetail: "林老师叉着腰看了一圈：大家都说会帮忙，可真要收的时候，谁先收、收多少就开始变难了。",
    hook: "林老师和朋友玩完积木，地上到处都是。",
    mainQuestion: "收玩具时，你觉得该每个人收一样多，还是谁弄乱得多谁多收一点？",
    firstFollowUp: "哪种办法更容易让大家点头？",
    twistFollowUp: "要是有个人今天手受伤了，你会不会改规则？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "rule-creation",
    coachFocus: "让孩子把公平和实际情况放在一起权衡。",
  },
  {
    id: "fairness-game-1",
    themeId: "fairness",
    title: "游戏规则要不要改",
    adaptationLevel: 2,
    sceneSetup: "这场小游戏才玩了两轮，同一个人已经赢得很轻松了。",
    sceneDetail: "林老师悄悄看了看旁边的人：大家嘴上没说，可脸上的表情已经有点不一样。",
    hook: "林老师发现一个游戏里，总是同一个人特别容易赢。",
    mainQuestion: "如果一个游戏老让同一个人轻松赢，你觉得要不要改规则？",
    firstFollowUp: "你最想先改哪一条？为什么？",
    twistFollowUp: "要是改完以后变得一点也不好玩，还算好规则吗？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "rule-creation",
    coachFocus: "训练孩子从“抱怨不公平”走到“提出更公平的规则”。",
  },
  {
    id: "fairness-team-1",
    themeId: "fairness",
    title: "输的一队先选还是赢的一队先选",
    adaptationLevel: 3,
    sceneSetup: "一轮比赛刚结束，两队都围到林老师身边，想知道下一轮谁先选。",
    sceneDetail: "林老师眨眨眼：我说一句话，可能就会让一边开心、一边皱眉。",
    hook: "林老师给下一轮比赛排先后顺序，结果大家意见不一样。",
    mainQuestion: "下一轮开始前，你觉得该让上一轮输的一队先选，还是赢的一队先选？",
    firstFollowUp: "这样安排，比较像是在帮谁？",
    twistFollowUp: "要是两队差得特别大，你会不会改主意？",
    suggestedInput: "voice",
    goalId: "strategy-thinking",
    subGoalId: "risk-assessment",
    coachFocus: "让孩子看到公平有时和“让比赛更接近”有关。",
  },
  {
    id: "fairness-story-1",
    themeId: "fairness",
    title: "讲故事轮到谁决定结尾",
    adaptationLevel: 3,
    sceneSetup: "故事已经讲到最后一段，大家都抢着说“让我来定结尾”。",
    sceneDetail: "林老师一边笑一边举手：我知道每个人都想收最后一下，可我也想让大家觉得顺气。",
    hook: "林老师和朋友轮流讲故事，大家都想最后一个定结尾。",
    mainQuestion: "讲故事时，谁来决定最后的结尾会比较公平？",
    firstFollowUp: "你会先想到轮流，还是别的办法？",
    twistFollowUp: "要是今天有人过生日，你会不会让规则变一下？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "rule-creation",
    coachFocus: "鼓励孩子看到规则既可以稳定，也可以因为情境而弹性调整。",
  },
  {
    id: "whatif-redlight-1",
    themeId: "what-if",
    title: "如果没有红灯",
    adaptationLevel: 1,
    sceneSetup: "林老师站在十字路口，红灯一闪一闪地把车和人都拦住了。",
    sceneDetail: "林老师突然抬头问你：要是这里一下子没有红灯了，最先乱掉的会是什么？",
    hook: "林老师今天突然蹦出一个大胆问题。",
    mainQuestion: "要是路口没有红灯，大家会怎么过马路？",
    firstFollowUp: "你觉得最先会冒出来的麻烦是什么？",
    twistFollowUp: "要是真的不能装红灯，你会想什么别的办法？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "hypothetical-thinking",
    coachFocus: "让孩子从假设情境里预测后果，再尝试设计替代方案。",
  },
  {
    id: "whatif-chair-1",
    themeId: "what-if",
    title: "如果少一把椅子",
    adaptationLevel: 1,
    sceneSetup: "上课前，小椅子一把一把摆好了，可怎么数都只数到 4 把。",
    sceneDetail: "林老师愣了一下：可这里已经站着 5 个小朋友了，等会儿最先会发生什么？",
    hook: "林老师准备上课时，忽然发现教室少了一把椅子。",
    mainQuestion: "要是 5 个小朋友只有 4 把椅子，大家会怎么办？",
    firstFollowUp: "哪种办法最不容易吵起来？",
    twistFollowUp: "要是明天还是少一把椅子，你会先改什么？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "hypothetical-thinking",
    coachFocus: "把“会发生什么”推进到“怎样更好地处理”。",
  },
  {
    id: "whatif-two-moons-1",
    themeId: "what-if",
    title: "如果天上有两个月亮",
    adaptationLevel: 2,
    sceneSetup: "林老师昨晚做梦时，一抬头，天上居然挂着两个月亮。",
    sceneDetail: "醒来以后林老师还记得那种亮亮的感觉：如果是真的，晚上会不会整个世界都不一样？",
    hook: "林老师昨晚做梦，梦见天上挂着两个月亮。",
    mainQuestion: "要是天上真的有两个月亮，晚上看起来会有什么不一样？",
    firstFollowUp: "你先想到的是更亮，还是别的变化？",
    twistFollowUp: "要是你要把这个世界画下来，你最想多画哪一部分？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "hypothetical-thinking",
    coachFocus: "让孩子练习从一个假设往外扩，形成多个可能变化。",
  },
  {
    id: "whatif-rule-1",
    themeId: "what-if",
    title: "如果教室没有规则",
    adaptationLevel: 3,
    sceneSetup: "林老师想象了一下，教室里所有规则突然一下子都消失了。",
    sceneDetail: "林老师忍不住笑了一下，又有点担心：刚开始也许很好玩，可第一个麻烦会是什么呢？",
    hook: "林老师想象了一下一个完全没有规则的教室。",
    mainQuestion: "要是教室里一条规则都没有，你觉得先会发生什么？",
    firstFollowUp: "你觉得哪一条规则其实最重要？",
    twistFollowUp: "要是只能留下一条规则，你会选哪一条？",
    suggestedInput: "voice",
    goalId: "logical-reasoning",
    subGoalId: "multi-step-reasoning",
    coachFocus: "从“乱不乱”走到“规则是为了解决什么问题”。",
  },
  {
    id: "whatif-book-1",
    themeId: "what-if",
    title: "如果一本书没有字",
    adaptationLevel: 2,
    sceneSetup: "林老师捡到一本厚厚的书，翻开以后每一页都干干净净，没有一个字。",
    sceneDetail: "林老师把书举给你看：可我总觉得它还是想讲一个故事，只是没用平常的方法。",
    hook: "林老师捡到一本神奇的书，翻开来一页字都没有。",
    mainQuestion: "要是一本书没有字，它还能怎么把故事讲给你听？",
    firstFollowUp: "你先想到的是图片、声音，还是别的方法？",
    twistFollowUp: "要是想让别人也看懂，你会加上什么提示？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "divergent-thinking",
    coachFocus: "鼓励孩子提出多种可能，再比较哪一种更容易被别人理解。",
  },
  {
    id: "whatif-rainbow-road-1",
    themeId: "what-if",
    title: "如果道路会变颜色",
    adaptationLevel: 3,
    sceneSetup: "林老师想象城市里的路像心情一样，会自己变颜色。",
    sceneDetail: "林老师一边走一边想：如果脚下的路突然变成别的颜色，人会不会一下子知道该快一点还是慢一点？",
    hook: "林老师想象城市里的路，会像心情一样变颜色。",
    mainQuestion: "要是道路会变颜色，你觉得不同颜色可以提醒大家什么？",
    firstFollowUp: "哪一种颜色最像在说“慢一点”？",
    twistFollowUp: "要是颜色太多，大家反而看不懂，你会怎么改？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "hypothetical-thinking",
    coachFocus: "让孩子从想象走到规则设计，看到好想法也需要清楚。",
  },
];

const scenarioQuestionIds = new Set(DAILY_SCENARIO_QUESTION_BANK.map((question) => question.id));

export const DAILY_QUESTION_BANK: DailyQuestion[] = [
  ...DAILY_SCENARIO_QUESTION_BANK,
  ...LEGACY_DAILY_QUESTION_BANK.filter((question) => !scenarioQuestionIds.has(question.id)),
];
