import type { DailyQuestion, ScenarioTemplate, ScenarioTemplateVariable } from "@/types/daily";

function variable(
  key: string,
  label: string,
  examples: string[],
  defaultValue = examples[0] ?? "",
): ScenarioTemplateVariable {
  return { key, label, examples, defaultValue };
}

function hashSeed(seed: string) {
  let hash = 0;
  for (let index = 0; index < seed.length; index += 1) {
    hash = (hash * 31 + seed.charCodeAt(index)) >>> 0;
  }
  return hash;
}

function pickVariableExample(variable: ScenarioTemplateVariable, seed: string) {
  const examples = variable.examples.length > 0
    ? variable.examples
    : [variable.defaultValue ?? ""];
  return examples[hashSeed(`${seed}:${variable.key}`) % examples.length] ?? variable.defaultValue ?? "";
}

export function buildScenarioTemplateVariables(
  template: ScenarioTemplate,
  seed: string,
): Record<string, string> {
  return Object.fromEntries(
    template.variables.map((item) => [item.key, pickVariableExample(item, `${seed}:${template.id}`)]),
  );
}

export function applyScenarioTemplateVariablesToText(
  value: string,
  template: ScenarioTemplate,
  selectedVariables: Record<string, string> = {},
) {
  return template.variables.reduce((next, item) => {
    const defaultValue = item.defaultValue ?? item.examples[0] ?? "";
    const selectedValue = selectedVariables[item.key] ?? defaultValue;
    if (!defaultValue || selectedValue === defaultValue) return next;
    return next.split(defaultValue).join(selectedValue);
  }, value);
}

function applyScenarioTemplateVariablesToList(
  values: string[],
  template: ScenarioTemplate,
  selectedVariables: Record<string, string>,
) {
  return values.map((value) =>
    applyScenarioTemplateVariablesToText(value, template, selectedVariables),
  );
}

export const DAILY_SCENARIO_TEMPLATES: ScenarioTemplate[] = [
  {
    id: "math-fruit-share-1",
    themeId: "math",
    title: "8 块水果怎么分",
    scenarioType: "quantity-sharing",
    levelRange: [1, 2],
    targetThinkingMoves: ["notice", "represent", "compare"],
    variables: [
      variable("items", "要分的东西", ["水果", "饼干", "贴纸"]),
      variable("people", "人数", ["3 个小朋友", "4 个小朋友"]),
    ],
    imagePrompt: "一盘水果和几个小朋友围在桌边，画面清楚显示数量，适合儿童观察分配。",
    sceneSetup: "林老师抱着一盘切好的水果，三个小朋友已经围到桌边了。",
    sceneDetail: "林老师压低声音说：我一分就怕有人皱眉，你帮我想个不容易吵起来的办法。",
    hook: "林老师想请你当今天的分水果队长。",
    openingQuestion: "3 个小朋友来分这 8 块水果，你会怎么分，大家比较容易点头？",
    scaffoldOptions: ["先一人一块地分", "先看能不能一样多", "先留下不好分的那一块"],
    conditionChanges: ["要是又来了第 4 个小朋友，你会怎么改？", "要是水果大小不一样，你还会这样分吗？"],
    evidenceTargets: ["指出数量差异", "说出分法理由", "比较一样多和比较公平"],
    wrapUpQuestion: "如果下次换成饼干，你会先看什么？",
    suggestedInput: "voice",
    goalId: "math-thinking",
    subGoalId: "quantity-comparison",
    progressionStageId: "foundation-observe",
    coachFocus: "引导孩子比较数量、解释差值，并发现平均分不整时也能讨论更公平的办法。",
  },
  {
    id: "math-shop-change-1",
    themeId: "math",
    title: "买两样东西要带多少钱",
    scenarioType: "quantity-composition",
    levelRange: [1, 2],
    targetThinkingMoves: ["represent", "explain"],
    variables: [
      variable("firstPrice", "第一样价格", ["6 元", "5 元"]),
      variable("secondPrice", "第二样价格", ["4 元", "3 元"]),
    ],
    imagePrompt: "小商店货架上有面包、牛奶和价格牌，价格数字大而清楚。",
    sceneSetup: "林老师站在小商店门口，口袋里只有几枚硬币在叮当响。",
    sceneDetail: "林老师把面包和牛奶指给你看，小声问：我不想带多了，也不想到柜台才发现不够。",
    hook: "林老师想先算好口袋里的钱。",
    openingQuestion: "一个面包 6 元，一盒牛奶 4 元。林老师最少带多少钱才一定够？",
    scaffoldOptions: ["先把 6 放在心里", "再加上 4", "用硬币摆一摆"],
    conditionChanges: ["要是林老师还想买 1 元的贴纸，你会先算哪一步？", "如果牛奶变成 5 元，答案会怎么变？"],
    evidenceTargets: ["用加合表征总数", "说出计算顺序", "条件变化后调整结果"],
    wrapUpQuestion: "你能把这个买法说成一句小办法吗？",
    suggestedInput: "voice",
    goalId: "math-thinking",
    subGoalId: "quantity-comparison",
    progressionStageId: "foundation-observe",
    coachFocus: "鼓励孩子把总数想清楚，再说出自己是怎么合起来的。",
  },
  {
    id: "math-shortcut-1",
    themeId: "math",
    title: "哪种数法更省劲",
    scenarioType: "strategy-comparison",
    levelRange: [2, 3],
    targetThinkingMoves: ["compare", "explain", "predict"],
    variables: [
      variable("count", "物品数量", ["12 颗扣子", "14 颗珠子"]),
      variable("strategy", "数法", ["一颗一颗数", "2 颗 2 颗数"]),
    ],
    imagePrompt: "地上整齐散着 12 颗扣子，旁边有一颗一颗数和两颗一组数的提示。",
    sceneSetup: "地上散着 12 颗亮亮的扣子，林老师已经蹲下来准备开始数了。",
    sceneDetail: "林老师抬头看看你：我想找一种又快又不容易数错的办法。",
    hook: "林老师想学一种更省劲的数法。",
    openingQuestion: "地上有 12 颗扣子，你会一颗一颗数，还是 2 颗 2 颗数？",
    scaffoldOptions: ["一颗一颗数更稳", "2 颗 2 颗数更快", "先摆成两排再数"],
    conditionChanges: ["要是变成 11 颗，这个办法还一样顺手吗？", "如果有一颗藏起来，你会怎么检查？"],
    evidenceTargets: ["比较两种策略", "说明省劲原因", "预测奇数变化的影响"],
    wrapUpQuestion: "你会怎么教别人用这个省劲办法？",
    suggestedInput: "choice",
    goalId: "math-thinking",
    subGoalId: "strategy-planning",
    progressionStageId: "strategy-pattern",
    coachFocus: "引导孩子比较不同策略的效率，并注意奇偶变化带来的影响。",
  },
  {
    id: "math-many-ways-1",
    themeId: "math",
    title: "7 可以拆成几种",
    scenarioType: "decomposition",
    levelRange: [1, 3],
    targetThinkingMoves: ["represent", "compare", "reflect"],
    variables: [variable("number", "要拆的数", ["7", "8", "9"])],
    imagePrompt: "桌上有 7 块小积木，左右两边各有一个空盘，适合表现拆分。",
    sceneSetup: "林老师把 7 块小积木推到桌子中间，左右各留了一小块空位。",
    sceneDetail: "林老师笑着说：我想把 7 拆开玩玩，可不想只想到一种。",
    hook: "数字积木今天想玩“拆一拆”的游戏。",
    openingQuestion: "7 可以拆成两个数，你先想到哪一组？",
    scaffoldOptions: ["先拆成 1 和 6", "想一组差不多的", "用积木摆两堆"],
    conditionChanges: ["要是两边要一样多，7 办得到吗？", "如果换成 8，你会先试哪一组？"],
    evidenceTargets: ["生成一种表征", "比较不同拆法", "发现奇偶限制"],
    wrapUpQuestion: "你能说说找拆法时先看什么吗？",
    suggestedInput: "text",
    goalId: "math-thinking",
    subGoalId: "quantity-comparison",
    progressionStageId: "foundation-observe",
    coachFocus: "鼓励孩子生成多种组合，再比较其中哪些更对称、更特别。",
  },
  {
    id: "math-stairs-1",
    themeId: "math",
    title: "上 10 级台阶怎么走",
    scenarioType: "step-planning",
    levelRange: [2, 4],
    targetThinkingMoves: ["predict", "compare", "reflect"],
    variables: [variable("steps", "台阶数", ["10 级", "9 级"])],
    imagePrompt: "10 级台阶从下往上清楚可见，旁边有一步一级和一步两级的脚印。",
    sceneSetup: "林老师站在 10 级台阶下面，已经把脚尖点到了第一格。",
    sceneDetail: "林老师边比划边说：我想快一点到上面，但也不想走着走着乱掉。",
    hook: "林老师站在楼梯口，想试试更聪明的走法。",
    openingQuestion: "要走上 10 级台阶，你会每次走 1 级，还是有时候走 2 级？",
    scaffoldOptions: ["每次 1 级更稳", "有时候 2 级更快", "先试一段再改"],
    conditionChanges: ["要是最后一级特别高，你会不会改办法？", "如果台阶变成 9 级，最后会不会不一样？"],
    evidenceTargets: ["预测走法结果", "比较快和稳", "根据条件调整策略"],
    wrapUpQuestion: "把你的上楼办法用一句话教给林老师。",
    suggestedInput: "voice",
    goalId: "math-thinking",
    subGoalId: "strategy-planning",
    progressionStageId: "strategy-pattern",
    coachFocus: "让孩子比较不同走法的节奏与结果，练习先想后做。",
  },
  {
    id: "math-seat-rows-1",
    themeId: "math",
    title: "12 个座位怎么排",
    scenarioType: "array-layout",
    levelRange: [1, 3],
    targetThinkingMoves: ["represent", "compare", "transfer"],
    variables: [variable("chairs", "椅子数量", ["12 把", "16 把"])],
    imagePrompt: "活动室里有 12 把小椅子，可以看见三排或四排的摆放可能。",
    sceneSetup: "教室角落里堆着 12 把小椅子，林老师正把它们一把一把拖出来。",
    sceneDetail: "林老师回头问你：我想摆得整齐一点，还得留地方让大家走来走去。",
    hook: "林老师想帮教室把小椅子摆得又整齐又好走。",
    openingQuestion: "12 把小椅子，排成 3 排还是 4 排，你会先怎么想？",
    scaffoldOptions: ["先算每排几把", "先留走路空位", "先画一个小图"],
    conditionChanges: ["要是中间还要留一条走路的空位，你会怎么摆？", "如果多来 4 个小朋友，排法要怎么变？"],
    evidenceTargets: ["用行列表征", "连接数量和空间", "迁移到新人数"],
    wrapUpQuestion: "你觉得摆椅子最重要的一条规则是什么？",
    suggestedInput: "voice",
    goalId: "math-thinking",
    subGoalId: "spatial-reasoning",
    progressionStageId: "foundation-observe",
    coachFocus: "把数量关系和空间摆放连起来，让孩子看到“数”和“形”是一起想的。",
  },
  {
    id: "math-rule-sentence-1",
    themeId: "math",
    title: "把排法说成一句规则",
    scenarioType: "rule-expression",
    levelRange: [3, 4],
    targetThinkingMoves: ["notice", "reflect", "transfer"],
    variables: [variable("pattern", "规律块", ["红红蓝", "黄黄绿"])],
    imagePrompt: "一串彩珠按红红蓝、红红蓝排列，最后留一个空位。",
    sceneSetup: "林老师把一串彩珠排成红红蓝、红红蓝，盯着看了一会儿。",
    sceneDetail: "林老师轻轻敲了敲桌子：我好像看出来了，可我想把这个排法说成一句短短的话。",
    hook: "林老师想练习把看见的规律说成一句小规则。",
    openingQuestion: "如果你要用一句短短的话把这个排法告诉林老师，你会怎么说？",
    scaffoldOptions: ["说重复哪一小段", "说每次怎么接下去", "先指一指再说"],
    conditionChanges: ["要是换成黄黄绿，你觉得还是同一家规则吗？", "如果中间多了一个红，这句话要不要改？"],
    evidenceTargets: ["说出重复块", "用自己的话总结规则", "迁移到不同颜色"],
    wrapUpQuestion: "这条规则换成动作，还能怎么做？",
    suggestedInput: "voice",
    goalId: "math-thinking",
    subGoalId: "pattern-recognition",
    progressionStageId: "rules-expression",
    coachFocus: "让孩子不只看见规律，还尝试把规律说成一条短规则。",
  },
  {
    id: "math-map-route-1",
    themeId: "math",
    title: "送书路线要不要改",
    scenarioType: "route-replanning",
    levelRange: [3, 4],
    targetThinkingMoves: ["predict", "compare", "transfer"],
    variables: [variable("obstacle", "挡路物", ["大桌子", "书架"])],
    imagePrompt: "教室俯视图，有三摞书、三个角落和中间挡路的大桌子。",
    sceneSetup: "林老师要把三摞书送到教室的三个角落，可教室中间忽然多出一张大桌子挡住了路。",
    sceneDetail: "林老师本来已经想好了一条顺路路线，现在又停下来重新看了一眼整个房间。",
    hook: "林老师想看看，原来的路线是不是还算最顺。",
    openingQuestion: "如果中间多了一张桌子，你会不会改送书路线？先怎么改？",
    scaffoldOptions: ["先绕开桌子", "先送最近的一摞", "先画路线"],
    conditionChanges: ["要是桌子换到另一边，你的路线会不会又变？", "如果只能走一次来回，你会先送哪里？"],
    evidenceTargets: ["预测障碍影响", "比较路线成本", "迁移到新位置"],
    wrapUpQuestion: "你能说出一条找路线的小规则吗？",
    suggestedInput: "voice",
    goalId: "math-thinking",
    subGoalId: "spatial-reasoning",
    progressionStageId: "story-reasoning",
    coachFocus: "让孩子把空间路线和连续变化放在一起考虑，形成迁移式调整。",
  },

  {
    id: "pattern-scarf-1",
    themeId: "pattern",
    title: "围巾花纹下一格",
    scenarioType: "visual-repeat",
    levelRange: [1, 2],
    targetThinkingMoves: ["notice", "represent", "explain"],
    variables: [variable("unit", "重复块", ["红红蓝", "绿黄绿"])],
    imagePrompt: "围巾花纹按红红蓝、红红蓝排列，最后留一个空格，颜色清晰。",
    sceneSetup: "林老师把一条围巾摊在桌上，花纹一格一格排得很整齐。",
    sceneDetail: "林老师用手指点着最后一格说：我总觉得它下一下应该继续唱下去。",
    hook: "林老师看到一条围巾，花纹排得像在唱歌。",
    openingQuestion: "花纹是红红蓝、红红蓝，下一格最像什么？",
    scaffoldOptions: ["先找重复的一小段", "从头小声念一遍", "用手指分成一组一组"],
    conditionChanges: ["要是中间偷偷多了一个黄点，会发生什么？", "如果颜色换了但节奏一样，还算同一种规律吗？"],
    evidenceTargets: ["指出下一项", "说出重复块", "解释为什么不是别的颜色"],
    wrapUpQuestion: "你能把这个规律说成一句短话吗？",
    suggestedInput: "choice",
    goalId: "observation-induction",
    subGoalId: "inductive-generalization",
    coachFocus: "让孩子先说出重复块，再讨论变化会不会打破原来的规则。",
  },
  {
    id: "pattern-steps-1",
    themeId: "pattern",
    title: "脚印在往哪边变",
    scenarioType: "alternating-sequence",
    levelRange: [1, 2],
    targetThinkingMoves: ["notice", "explain"],
    variables: [variable("sequence", "方向序列", ["左、右、左、右", "前、后、前、后"])],
    imagePrompt: "沙地上有左脚、右脚交替的脚印，下一格为空。",
    sceneSetup: "沙地上留下了一串脚印，左一下、右一下，一直往前伸。",
    sceneDetail: "林老师蹲下来眯着眼睛看：它们像在排队，可又像在偷偷给我提示。",
    hook: "林老师在沙地上发现一串左一下、右一下的脚印。",
    openingQuestion: "脚印如果是左、右、左、右，接下来该是哪一只？",
    scaffoldOptions: ["先从第一只念起", "看它是不是轮流", "用自己的脚试一试"],
    conditionChanges: ["要是后面突然连着出现两个右脚印，你会怎么解释？", "如果换成拍手跺脚，还能用这个规律吗？"],
    evidenceTargets: ["指出轮流关系", "解释不是另一只", "处理例外"],
    wrapUpQuestion: "你能说出这个脚印规律的名字吗？",
    suggestedInput: "voice",
    goalId: "observation-induction",
    subGoalId: "systematic-observation",
    coachFocus: "鼓励孩子明确说出排列顺序，并学习反驳错误可能。",
  },
  {
    id: "pattern-tower-1",
    themeId: "pattern",
    title: "积木塔每次怎么变",
    scenarioType: "growing-pattern",
    levelRange: [2, 3],
    targetThinkingMoves: ["represent", "explain", "predict"],
    variables: [variable("growth", "增长量", ["每次多 2 块", "每次多 1 层"])],
    imagePrompt: "三座积木塔分别有 2、4、6 块，第四座位置为空。",
    sceneSetup: "林老师在地上摆了三座积木塔，一座比一座高。",
    sceneDetail: "林老师指着第三座说：我觉得后面这座应该也有自己的脾气，不会乱长。",
    hook: "林老师搭了一排积木塔，每一座都悄悄变高一点。",
    openingQuestion: "第一座 2 块，第二座 4 块，第三座 6 块。你猜下一座会怎样？",
    scaffoldOptions: ["看每次多几个", "把数字写成 2、4、6", "用积木接着搭"],
    conditionChanges: ["要是第四座只有 7 块，你会不会觉得怪怪的？", "如果从 3、5、7 开始，下一座像什么？"],
    evidenceTargets: ["说出每次增加量", "预测下一项", "检查例外"],
    wrapUpQuestion: "把这个长高规则用一句话说出来。",
    suggestedInput: "voice",
    goalId: "observation-induction",
    subGoalId: "inductive-generalization",
    coachFocus: "让孩子区分“每次加多少”和“最后是多少”，避免只记结果不记规则。",
  },
  {
    id: "pattern-clap-1",
    themeId: "pattern",
    title: "拍手节奏少了什么",
    scenarioType: "sound-pattern",
    levelRange: [2, 3],
    targetThinkingMoves: ["represent", "compare", "transfer"],
    variables: [variable("rhythm", "节奏块", ["拍拍停", "拍停停"])],
    imagePrompt: "用图标表现拍拍停、拍拍停，中间有一个空白节拍。",
    sceneSetup: "林老师边走边拍手，拍拍停、拍拍停，可是中间突然卡了一下。",
    sceneDetail: "林老师笑着耸耸肩：我明明差一点就拍顺了，你帮我把那一下找回来。",
    hook: "林老师在练拍手节奏，可是中间漏了一下。",
    openingQuestion: "节奏是拍拍停、拍拍停，少掉的那一下应该是什么？",
    scaffoldOptions: ["先拍一遍", "把拍和停画成图标", "找一组一组重复"],
    conditionChanges: ["要是改成拍停停，这个节奏会像什么？", "如果换成跺脚和停，还能接上吗？"],
    evidenceTargets: ["把声音表征成结构", "找缺失项", "迁移到动作"],
    wrapUpQuestion: "这个节奏的重复块是什么？",
    suggestedInput: "choice",
    goalId: "observation-induction",
    subGoalId: "systematic-observation",
    coachFocus: "把声音规律说成看得见的节奏块，帮助孩子从听觉转成结构。",
  },
  {
    id: "pattern-window-1",
    themeId: "pattern",
    title: "窗户亮灯顺序",
    scenarioType: "grouped-repeat",
    levelRange: [3, 4],
    targetThinkingMoves: ["compare", "explain", "reflect"],
    variables: [variable("unit", "重复块", ["左、左、右", "上、上、下"])],
    imagePrompt: "夜晚大楼窗户按左、左、右、左、左、右亮灯，下一格为空。",
    sceneSetup: "晚上，大楼一格一格亮灯，像有人在空中悄悄打信号。",
    sceneDetail: "林老师抬头看了好久：我总觉得这些灯不是乱亮的，它们像在按自己的顺序眨眼。",
    hook: "林老师晚上看见大楼的窗户一格一格亮起来。",
    openingQuestion: "亮灯顺序是左、左、右、左、左、右，下一格最像会亮哪边？",
    scaffoldOptions: ["试着分成三格一组", "比较两格一组和三格一组", "找重复块的开头"],
    conditionChanges: ["要是最后一格改成中间那扇窗，这个规律还像原来的吗？", "如果换成声音，你会怎么敲出来？"],
    evidenceTargets: ["说出重复块长度", "比较可能规则", "说明错误项哪里错"],
    wrapUpQuestion: "你怎么判断它是一组三格？",
    suggestedInput: "voice",
    goalId: "observation-induction",
    subGoalId: "inductive-generalization",
    coachFocus: "让孩子把重复块长度说出来，而不是只凭感觉报答案。",
  },
  {
    id: "pattern-turn-1",
    themeId: "pattern",
    title: "箭头在转圈吗",
    scenarioType: "rotation-pattern",
    levelRange: [3, 4],
    targetThinkingMoves: ["represent", "predict", "transfer"],
    variables: [variable("direction", "方向变化", ["上、右、下", "左、上、右"])],
    imagePrompt: "箭头卡片依次朝上、朝右、朝下，第四张卡片留空。",
    sceneSetup: "桌上的小箭头卡片一张张摆开，看上去像在慢慢转弯。",
    sceneDetail: "林老师把最后一张卡住不放：我总觉得它下一下会继续转，可我想先听你怎么说。",
    hook: "林老师看到小箭头，好像每次都在转一点点。",
    openingQuestion: "箭头先朝上，再朝右，再朝下。你猜接下来会朝哪边？",
    scaffoldOptions: ["用手转一转", "画一个方向圈", "想每次转多少"],
    conditionChanges: ["要是它下一次又朝上，你会觉得它其实是什么规则？", "如果换成小车转弯，还能用这个规则吗？"],
    evidenceTargets: ["表征旋转", "预测下一方向", "迁移到不同物体"],
    wrapUpQuestion: "这个箭头每次都在怎么变？",
    suggestedInput: "voice",
    goalId: "observation-induction",
    subGoalId: "analogy-transfer",
    coachFocus: "把方向变化说成可迁移的规则，帮助孩子把图形变化和顺序规律联系起来。",
  },
  {
    id: "pattern-bracelet-1",
    themeId: "pattern",
    title: "手链珠子哪里错了",
    scenarioType: "error-check",
    levelRange: [3, 4],
    targetThinkingMoves: ["notice", "compare", "reflect"],
    variables: [variable("unit", "珠子规律", ["红蓝绿", "黄黄紫"])],
    imagePrompt: "一串手链珠子大多按红蓝绿重复，中间有一颗颜色打乱。",
    sceneSetup: "林老师穿手链时发现有一小段看起来不太顺。",
    sceneDetail: "她没有急着重穿，只把手链放到你面前：我想先知道是哪一颗让规律歪了一点。",
    hook: "林老师想请你当手链检查员。",
    openingQuestion: "如果珠子本来是红蓝绿、红蓝绿，中间多了一个红，你会觉得哪里不对？",
    scaffoldOptions: ["先找原来的重复块", "把中间多出来的地方圈出来", "比较前后两组"],
    conditionChanges: ["如果多的是蓝，不对的地方会变吗？", "要是少了一颗绿，你会怎么补？"],
    evidenceTargets: ["发现破坏规律的位置", "用证据比较前后", "提出修正办法"],
    wrapUpQuestion: "你会怎么检查一串很长的手链？",
    suggestedInput: "voice",
    goalId: "observation-induction",
    subGoalId: "systematic-observation",
    coachFocus: "从找下一项推进到检查错误，让孩子用证据修正规则。",
  },
  {
    id: "pattern-dance-1",
    themeId: "pattern",
    title: "把颜色规律变成舞步",
    scenarioType: "cross-modal-transfer",
    levelRange: [4, 4],
    targetThinkingMoves: ["transfer", "represent", "reflect"],
    variables: [variable("sourcePattern", "原规律", ["红红蓝", "拍拍停"])],
    imagePrompt: "左边是红红蓝颜色卡，右边是跳跳拍动作卡，表现同一种重复结构。",
    sceneSetup: "林老师把颜色卡片收起来，换成了小动作卡。",
    sceneDetail: "她眨眨眼：如果规律不是用颜色唱，而是用身体跳出来，会不会还是同一个规律？",
    hook: "林老师想把规律从眼睛搬到身体里。",
    openingQuestion: "红红蓝这个规律，如果换成动作，你会怎么跳？",
    scaffoldOptions: ["红换成跳", "蓝换成拍手", "先保留两下一下的结构"],
    conditionChanges: ["如果换成声音，你会怎么敲？", "要是动作变了但结构没变，还算同一种规律吗？"],
    evidenceTargets: ["跨表现形式迁移", "保留结构不只记颜色", "自己造同类规律"],
    wrapUpQuestion: "你怎么知道两个规律是同一家？",
    suggestedInput: "voice",
    goalId: "observation-induction",
    subGoalId: "analogy-transfer",
    coachFocus: "让孩子把表面颜色背后的结构迁移到动作、声音等新形式。",
  },

  {
    id: "why-shadow-1",
    themeId: "why",
    title: "影子为什么跟着走",
    scenarioType: "cause-explanation",
    levelRange: [1, 2],
    targetThinkingMoves: ["notice", "explain", "predict"],
    variables: [variable("lightSource", "光源", ["太阳", "手电筒"])],
    imagePrompt: "阳光下一个小朋友和清楚的影子，云遮住太阳的变化也可见。",
    sceneSetup: "太阳底下，林老师跑到哪，脚边那团黑影就跟到哪。",
    sceneDetail: "林老师停下来回头看了两次：我明明没拉着它，它怎么还是跟来了？",
    hook: "林老师今天在太阳下跑步，发现影子一直黏着自己。",
    openingQuestion: "你觉得影子为什么会跟着人走？",
    scaffoldOptions: ["先想太阳在哪里", "想人挡住了什么", "说一个可能的因为"],
    conditionChanges: ["要是太阳躲到云后面，影子会怎么样？", "要是晚上开手电筒，影子会不会又跑出来？"],
    evidenceTargets: ["提出原因猜想", "用因为连接现象", "预测光源变化"],
    wrapUpQuestion: "如果想验证你的想法，可以怎么试？",
    suggestedInput: "voice",
    goalId: "language-thinking",
    subGoalId: "explain-reasoning",
    coachFocus: "鼓励孩子先大胆猜，再用“因为”把自己的想法说完整。",
  },
  {
    id: "why-ice-1",
    themeId: "why",
    title: "冰为什么会变成水",
    scenarioType: "state-change",
    levelRange: [1, 2],
    targetThinkingMoves: ["notice", "explain", "predict"],
    variables: [variable("place", "放置地点", ["桌上", "窗边"])],
    imagePrompt: "桌上一小块冰正在融化成水，旁边有温暖的空气或太阳光提示。",
    sceneSetup: "林老师把一小块冰放在桌上，刚开始它硬硬的、亮亮的。",
    sceneDetail: "过一会儿，桌上只剩下一小摊水，林老师皱了皱鼻子：它刚才明明不是这样的。",
    hook: "林老师把一小块冰放在桌上，过一会儿它就变样了。",
    openingQuestion: "你觉得冰为什么会慢慢变成水？",
    scaffoldOptions: ["先看它在哪里", "想周围冷还是热", "说一个可能原因"],
    conditionChanges: ["要是把它放回冰箱，它会怎么样？", "如果放在太阳底下，会不会更快？"],
    evidenceTargets: ["联系温度经验", "补充原因", "预测条件变化"],
    wrapUpQuestion: "你会怎么让冰慢一点变成水？",
    suggestedInput: "voice",
    goalId: "language-thinking",
    subGoalId: "explain-reasoning",
    coachFocus: "让孩子从生活经验出发说原因，不追求标准答案，先鼓励解释。",
  },
  {
    id: "why-plant-1",
    themeId: "why",
    title: "植物为什么爱窗边",
    scenarioType: "living-thing-cause",
    levelRange: [2, 3],
    targetThinkingMoves: ["notice", "explain", "predict"],
    variables: [variable("plant", "植物", ["小绿植", "豆苗"])],
    imagePrompt: "窗边小植物的叶子朝向亮处，花盆被转了一点。",
    sceneSetup: "窗边的小植物一整天都把叶子歪向亮亮的地方。",
    sceneDetail: "林老师把花盆轻轻转了一点：咦，它会不会过几天又悄悄转回去？",
    hook: "林老师发现窗边的小植物，总爱歪向亮亮的地方。",
    openingQuestion: "你觉得它为什么老想靠近窗边？",
    scaffoldOptions: ["先说你看见的样子", "想窗边有什么", "用因为补一句"],
    conditionChanges: ["要是把花盆转个方向，它会不会又慢慢转回来？", "要是窗帘一直拉着，它可能会怎样？"],
    evidenceTargets: ["描述观察", "构建解释", "预测条件变化"],
    wrapUpQuestion: "如果想照顾它，你会先做什么？",
    suggestedInput: "voice",
    goalId: "language-thinking",
    subGoalId: "describe-observation",
    coachFocus: "引导孩子先说看到的现象，再尝试解释原因。",
  },
  {
    id: "why-friend-1",
    themeId: "why",
    title: "朋友为什么突然不开心",
    scenarioType: "social-cause",
    levelRange: [3, 4],
    targetThinkingMoves: ["explain", "compare", "reflect"],
    variables: [variable("emotion", "情绪变化", ["突然不开心", "突然安静"])],
    imagePrompt: "一个孩子从笑到安静低头，旁边朋友保持距离并关心观察。",
    sceneSetup: "刚才还在笑的小朋友，忽然低下头，不说话了。",
    sceneDetail: "林老师也跟着安静下来：我不太想乱猜，可我又想知道是不是哪里不对了。",
    hook: "林老师看到一个小朋友刚刚还笑着，后来突然安静了。",
    openingQuestion: "你觉得一个人突然不开心，可能会是为什么？",
    scaffoldOptions: ["想一个可能原因", "再想一个不一样的原因", "先问问对方愿不愿意说"],
    conditionChanges: ["要是你不确定真正原因，你会先怎么做？", "要是换成你自己不开心，你希望别人怎么问你？"],
    evidenceTargets: ["提出多个原因", "比较原因可能性", "反思合适做法"],
    wrapUpQuestion: "你能想一句温柔又不乱猜的话吗？",
    suggestedInput: "voice",
    goalId: "language-thinking",
    subGoalId: "explain-reasoning",
    coachFocus: "把解释和同理心放在一起，让孩子学会提出多种可能。",
  },
  {
    id: "why-rain-1",
    themeId: "why",
    title: "为什么下雨后会有小水坑",
    scenarioType: "surface-difference",
    levelRange: [2, 3],
    targetThinkingMoves: ["notice", "compare", "explain"],
    variables: [variable("surface", "路面", ["坑坑洼洼的小路", "平平的操场"])],
    imagePrompt: "雨后路面有的地方积水、有的地方干，地面高低差清楚。",
    sceneSetup: "雨刚停，地上这里一小摊、那里一小摊，亮亮地照着天光。",
    sceneDetail: "林老师踩了一脚水坑又退回来：为什么同一条路上，有的地方有水，有的地方却干干的？",
    hook: "林老师最喜欢踩水坑，可也老想知道水坑是怎么来的。",
    openingQuestion: "雨停以后，地上为什么会有一块一块的小水坑？",
    scaffoldOptions: ["先比哪里低哪里高", "想水会往哪里跑", "说一个因为"],
    conditionChanges: ["要是第二天太阳很大，这些水坑会怎么样？", "如果地面很平，还会有很多水坑吗？"],
    evidenceTargets: ["观察差异", "比较地面条件", "解释水聚集原因"],
    wrapUpQuestion: "你会怎么找最容易积水的地方？",
    suggestedInput: "voice",
    goalId: "language-thinking",
    subGoalId: "describe-observation",
    coachFocus: "训练孩子把观察到的差异说出来，再往后推原因。",
  },
  {
    id: "why-socks-1",
    themeId: "why",
    title: "袜子为什么会只剩一只",
    scenarioType: "multiple-causes",
    levelRange: [3, 4],
    targetThinkingMoves: ["explain", "compare", "reflect"],
    variables: [variable("missingItem", "丢失物", ["袜子", "手套"])],
    imagePrompt: "洗衣篮和晾衣架上有成对袜子，其中一只缺少搭档。",
    sceneSetup: "洗好的袜子一只只挂着，偏偏只少了一个搭档。",
    sceneDetail: "林老师把洗衣篮翻了一遍，还是没找到：它到底是自己躲起来了，还是被谁带走了？",
    hook: "林老师今天洗袜子，结果只找到一只。",
    openingQuestion: "你觉得袜子为什么有时候会只剩下一只？",
    scaffoldOptions: ["想一个地方没找", "想洗衣时发生了什么", "一下子想两个原因"],
    conditionChanges: ["要是想让下次更容易找到，你会想什么办法？", "如果每次都少一只，哪个原因更像？"],
    evidenceTargets: ["生成多个解释", "比较原因可能性", "从原因到办法"],
    wrapUpQuestion: "你想设计一条防丢袜子规则吗？",
    suggestedInput: "voice",
    goalId: "language-thinking",
    subGoalId: "explain-reasoning",
    coachFocus: "鼓励孩子提出多种解释，再从解释走到办法。",
  },
  {
    id: "why-cloud-gray-1",
    themeId: "why",
    title: "云为什么会变灰",
    scenarioType: "weather-evidence",
    levelRange: [2, 3],
    targetThinkingMoves: ["notice", "explain", "compare"],
    variables: [variable("cloud", "天气现象", ["灰云", "白云"])],
    imagePrompt: "天空里一边是白云，一边是厚厚的灰云，下面光线变暗。",
    sceneSetup: "林老师抬头看见一朵云慢慢变厚，地面也跟着暗了一点。",
    sceneDetail: "她有点好奇：明明都是云，为什么有的看起来白白的，有的灰灰的？",
    hook: "林老师想知道云的颜色为什么会变。",
    openingQuestion: "你觉得云为什么有时候会变灰？",
    scaffoldOptions: ["先比较白云和灰云", "想云厚一点会怎样", "说一个你猜的原因"],
    conditionChanges: ["要是太阳从云后面出来，颜色会不会变？", "如果云很薄，还会灰灰的吗？"],
    evidenceTargets: ["比较两个现象", "提出厚薄或光线原因", "根据条件修正解释"],
    wrapUpQuestion: "你会怎么判断一朵云可能要下雨？",
    suggestedInput: "voice",
    goalId: "language-thinking",
    subGoalId: "explain-reasoning",
    coachFocus: "让孩子在自然现象里用观察差异支持原因猜想。",
  },
  {
    id: "why-toy-break-1",
    themeId: "why",
    title: "玩具车为什么跑歪了",
    scenarioType: "mechanism-check",
    levelRange: [3, 4],
    targetThinkingMoves: ["explain", "compare", "reflect"],
    variables: [variable("toy", "玩具", ["玩具车", "小飞机"])],
    imagePrompt: "一辆玩具车向一边跑歪，轮子和地面能看清楚。",
    sceneSetup: "林老师推了一下玩具车，它没有直直往前跑，而是慢慢歪到一边。",
    sceneDetail: "她没有马上修，先把车翻过来看：我想知道问题可能藏在哪里。",
    hook: "林老师想当一次小小修理员。",
    openingQuestion: "玩具车为什么可能会跑歪？",
    scaffoldOptions: ["先看轮子", "再看地面", "想两个可能原因"],
    conditionChanges: ["如果换到平地上还是跑歪，哪个原因更像？", "要是只有一个轮子卡住，你会怎么修？"],
    evidenceTargets: ["提出机制原因", "比较地面和轮子", "用测试修正猜想"],
    wrapUpQuestion: "你会先做哪一步检查？为什么？",
    suggestedInput: "voice",
    goalId: "language-thinking",
    subGoalId: "explain-reasoning",
    coachFocus: "把原因猜想推进到验证步骤，让孩子知道解释可以被检查。",
  },

  {
    id: "fairness-cookies-1",
    themeId: "fairness",
    title: "两块饼干算公平吗",
    scenarioType: "equal-vs-fair",
    levelRange: [1, 2],
    targetThinkingMoves: ["notice", "compare", "reflect"],
    variables: [variable("snack", "点心", ["饼干", "水果"])],
    imagePrompt: "几个孩子分饼干，有的人很饿，有的人刚吃过，盘子里数量清楚。",
    sceneSetup: "盘子里只剩下几块饼干，可每个人都已经把手伸过来了。",
    sceneDetail: "林老师边数边皱眉：如果每个人都拿一样多，是不是就一定没人心里别扭？",
    hook: "林老师今天要分点心，可每个人的肚子都不一样。",
    openingQuestion: "如果每个人都分到 2 块饼干，就一定算公平吗？",
    scaffoldOptions: ["一样多很清楚", "特别饿的人可能需要多一点", "先问大家需不需要"],
    conditionChanges: ["要是有一个人今天特别饿，你会怎么想？", "如果有人不喜欢饼干，规则要不要变？"],
    evidenceTargets: ["指出不公平线索", "比较一样多和合适", "反思规则边界"],
    wrapUpQuestion: "你觉得公平一定等于一样多吗？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "rule-creation",
    coachFocus: "让孩子开始区分“平均”与“合理”，不是只接受一个唯一答案。",
  },
  {
    id: "fairness-lineup-1",
    themeId: "fairness",
    title: "排队先后怎么定",
    scenarioType: "turn-taking-rule",
    levelRange: [1, 3],
    targetThinkingMoves: ["compare", "predict", "reflect"],
    variables: [variable("activity", "活动", ["滑梯", "秋千"])],
    imagePrompt: "滑梯口几个孩子排队，有一个年纪小，一个刚摔倒，队伍清楚。",
    sceneSetup: "滑梯口已经排起小队，后面的人一边踮脚一边往前看。",
    sceneDetail: "林老师站在旁边有点发愁：我定规则的时候，最怕有人一下子觉得不服气。",
    hook: "林老师要带大家玩滑梯，可每个人都想先上。",
    openingQuestion: "排队时，你会定先来先玩，还是年纪小的先玩？",
    scaffoldOptions: ["先来先玩更清楚", "年纪小先玩更照顾", "先问有没有特殊情况"],
    conditionChanges: ["要是有个小朋友刚刚摔倒了，你的规则要不要变一下？", "如果队伍特别长，要不要限制每个人时间？"],
    evidenceTargets: ["比较两条规则", "预测谁受影响", "根据变化调整规则"],
    wrapUpQuestion: "你想定一条大家比较服气的排队规则吗？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "rule-creation",
    coachFocus: "引导孩子设计规则、说出理由，并接受“规则也可能要改”。",
  },
  {
    id: "fairness-cleanup-1",
    themeId: "fairness",
    title: "收拾玩具怎么分工",
    scenarioType: "responsibility-rule",
    levelRange: [2, 3],
    targetThinkingMoves: ["compare", "transfer", "reflect"],
    variables: [variable("mess", "要收拾的东西", ["积木", "画笔"])],
    imagePrompt: "地上很多积木，几个孩子玩完准备收拾，其中有人手受伤。",
    sceneSetup: "玩完积木后，地上铺得满满的，箱子却还空着。",
    sceneDetail: "林老师叉着腰看了一圈：大家都说会帮忙，可真要收的时候，谁先收、收多少就开始变难了。",
    hook: "林老师和朋友玩完积木，地上到处都是。",
    openingQuestion: "收玩具时，你觉得该每个人收一样多，还是谁弄乱得多谁多收一点？",
    scaffoldOptions: ["每个人一样多", "谁弄乱多谁多收", "先按能力分工"],
    conditionChanges: ["要是有个人今天手受伤了，你会不会改规则？", "如果有人没玩这个玩具，还要一起收吗？"],
    evidenceTargets: ["比较责任规则", "照顾能力变化", "提出可执行规则"],
    wrapUpQuestion: "你的规则会让谁觉得被照顾到了？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "rule-creation",
    coachFocus: "让孩子把公平和实际情况放在一起权衡。",
  },
  {
    id: "fairness-game-1",
    themeId: "fairness",
    title: "游戏规则要不要改",
    scenarioType: "game-balance",
    levelRange: [2, 4],
    targetThinkingMoves: ["notice", "compare", "reflect"],
    variables: [variable("game", "游戏", ["投球", "跳格子"])],
    imagePrompt: "一个孩子连续赢游戏，其他孩子表情有点失落，规则卡在旁边。",
    sceneSetup: "这场小游戏才玩了两轮，同一个人已经赢得很轻松了。",
    sceneDetail: "林老师悄悄看了看旁边的人：大家嘴上没说，可脸上的表情已经有点不一样。",
    hook: "林老师发现一个游戏里，总是同一个人特别容易赢。",
    openingQuestion: "如果一个游戏老让同一个人轻松赢，你觉得要不要改规则？",
    scaffoldOptions: ["先看大家还想不想玩", "给新手一点帮助", "换一个计分办法"],
    conditionChanges: ["要是改完以后变得一点也不好玩，还算好规则吗？", "如果高手也觉得没挑战，规则该怎么调？"],
    evidenceTargets: ["看见不公平信号", "比较公平和好玩", "修正规则"],
    wrapUpQuestion: "你能设计一条既公平又好玩的规则吗？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "rule-creation",
    coachFocus: "训练孩子从“抱怨不公平”走到“提出更公平的规则”。",
  },
  {
    id: "fairness-team-1",
    themeId: "fairness",
    title: "输的一队先选还是赢的一队先选",
    scenarioType: "competitive-balance",
    levelRange: [3, 4],
    targetThinkingMoves: ["compare", "predict", "reflect"],
    variables: [variable("advantage", "优势", ["先选队友", "先拿道具"])],
    imagePrompt: "两队比赛后围在一起讨论下一轮谁先选，一边赢一边输。",
    sceneSetup: "一轮比赛刚结束，两队都围到林老师身边，想知道下一轮谁先选。",
    sceneDetail: "林老师眨眨眼：我说一句话，可能就会让一边开心、一边皱眉。",
    hook: "林老师给下一轮比赛排先后顺序，结果大家意见不一样。",
    openingQuestion: "下一轮开始前，你觉得该让上一轮输的一队先选，还是赢的一队先选？",
    scaffoldOptions: ["输的一队先选让比赛接近", "赢的一队先选像奖励", "轮流先选最简单"],
    conditionChanges: ["要是两队差得特别大，你会不会改主意？", "如果每轮都同一队输，规则要不要帮一下？"],
    evidenceTargets: ["比较奖励和补偿", "预测比赛差距", "反思规则目的"],
    wrapUpQuestion: "你的规则是想让比赛更公平，还是更刺激？",
    suggestedInput: "voice",
    goalId: "strategy-thinking",
    subGoalId: "risk-assessment",
    coachFocus: "让孩子看到公平有时和“让比赛更接近”有关。",
  },
  {
    id: "fairness-story-1",
    themeId: "fairness",
    title: "讲故事轮到谁决定结尾",
    scenarioType: "creative-turn-taking",
    levelRange: [3, 4],
    targetThinkingMoves: ["compare", "transfer", "reflect"],
    variables: [variable("role", "决定权", ["结尾", "角色名字"])],
    imagePrompt: "几个孩子围坐讲故事，每个人都举手想决定故事结尾。",
    sceneSetup: "故事已经讲到最后一段，大家都抢着说“让我来定结尾”。",
    sceneDetail: "林老师一边笑一边举手：我知道每个人都想收最后一下，可我也想让大家觉得顺气。",
    hook: "林老师和朋友轮流讲故事，大家都想最后一个定结尾。",
    openingQuestion: "讲故事时，谁来决定最后的结尾会比较公平？",
    scaffoldOptions: ["轮流决定", "抽签决定", "让今天没决定过的人来"],
    conditionChanges: ["要是今天有人过生日，你会不会让规则变一下？", "如果有人每次都抢着说，规则要怎么保护别人？"],
    evidenceTargets: ["设计轮流规则", "处理特殊情境", "迁移到其他决定权"],
    wrapUpQuestion: "你会怎么让每个人都有被听见的机会？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "rule-creation",
    coachFocus: "鼓励孩子看到规则既可以稳定，也可以因为情境而弹性调整。",
  },
  {
    id: "fairness-art-supplies-1",
    themeId: "fairness",
    title: "彩笔不够怎么借",
    scenarioType: "resource-sharing",
    levelRange: [2, 3],
    targetThinkingMoves: ["notice", "compare", "predict"],
    variables: [variable("resource", "共享资源", ["彩笔", "剪刀"])],
    imagePrompt: "桌上彩笔数量不够，几个孩子都要用不同颜色画画。",
    sceneSetup: "美工桌上只剩几支彩笔，可大家的画都还没画完。",
    sceneDetail: "林老师看见有人一直拿着最想要的颜色，旁边的人已经等了很久。",
    hook: "林老师想让彩笔在大家手里流动起来。",
    openingQuestion: "如果彩笔不够每个人一套，你会怎么定借用规则？",
    scaffoldOptions: ["每人用一会儿就换", "先给快用完的人", "按颜色轮流借"],
    conditionChanges: ["如果有人只差最后一笔，你会让他先用吗？", "要是有人一直不还，规则要怎么改？"],
    evidenceTargets: ["看见等待和占用", "比较轮流规则", "预测执行问题"],
    wrapUpQuestion: "你的规则怎样提醒大家记得还？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "rule-creation",
    coachFocus: "让孩子把稀缺资源、等待时间和可执行提醒放在一起想。",
  },
  {
    id: "fairness-helper-1",
    themeId: "fairness",
    title: "谁先得到帮助",
    scenarioType: "need-based-priority",
    levelRange: [3, 4],
    targetThinkingMoves: ["compare", "predict", "reflect"],
    variables: [variable("need", "需要帮助的事", ["系鞋带", "找书包"])],
    imagePrompt: "两个孩子同时需要帮助，一个很着急，一个可以等一下，老师在中间。",
    sceneSetup: "两个小朋友同时举手喊林老师，一个鞋带散了，一个想找彩纸。",
    sceneDetail: "林老师只有一双手，她不想让任何人觉得自己被忽略了。",
    hook: "林老师需要决定先帮谁。",
    openingQuestion: "如果两个人同时需要帮忙，你觉得林老师先帮谁比较合适？",
    scaffoldOptions: ["先帮更着急的人", "先帮很快能解决的人", "先说清楚谁等一下"],
    conditionChanges: ["如果等的人开始难过，你会怎么说？", "要是其中一个有危险，规则要不要立刻变？"],
    evidenceTargets: ["比较需要和等待", "预测感受影响", "设计说明方式"],
    wrapUpQuestion: "你能说一条又照顾安全又照顾感受的规则吗？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "rule-creation",
    coachFocus: "把公平推进到优先级与沟通，让孩子看到需要不同，规则也要说明白。",
  },

  {
    id: "whatif-redlight-1",
    themeId: "what-if",
    title: "如果没有红灯",
    scenarioType: "system-removal",
    levelRange: [1, 4],
    targetThinkingMoves: ["predict", "compare", "reflect"],
    variables: [variable("rule", "消失的规则", ["红灯", "斑马线"])],
    imagePrompt: "十字路口红灯消失，行人和车辆都停在路口边缘等待办法。",
    sceneSetup: "林老师站在十字路口，红灯一闪一闪地把车和人都拦住了。",
    sceneDetail: "林老师突然抬头问你：要是这里一下子没有红灯了，最先乱掉的会是什么？",
    hook: "林老师今天突然蹦出一个大胆问题。",
    openingQuestion: "要是路口没有红灯，大家会怎么过马路？",
    scaffoldOptions: ["车可能会抢先", "人会等别人先走", "需要一个新信号"],
    conditionChanges: ["要是真的不能装红灯，你会想什么别的办法？", "如果只有小路口没有红灯，会一样危险吗？"],
    evidenceTargets: ["预测第一步后果", "比较替代办法", "设计新规则"],
    wrapUpQuestion: "你会用什么办法替代红灯？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "hypothetical-thinking",
    coachFocus: "让孩子从假设情境里预测后果，再尝试设计替代方案。",
  },
  {
    id: "whatif-chair-1",
    themeId: "what-if",
    title: "如果少一把椅子",
    scenarioType: "resource-shortage",
    levelRange: [1, 3],
    targetThinkingMoves: ["predict", "compare", "reflect"],
    variables: [variable("resource", "短缺资源", ["椅子", "杯子"])],
    imagePrompt: "5 个小朋友站在教室里，只有 4 把椅子，缺少情况清楚。",
    sceneSetup: "上课前，小椅子一把一把摆好了，可怎么数都只数到 4 把。",
    sceneDetail: "林老师愣了一下：可这里已经站着 5 个小朋友了，等会儿最先会发生什么？",
    hook: "林老师准备上课时，忽然发现教室少了一把椅子。",
    openingQuestion: "要是 5 个小朋友只有 4 把椅子，大家会怎么办？",
    scaffoldOptions: ["先轮流坐", "再搬一把来", "请一个人先坐垫子"],
    conditionChanges: ["要是明天还是少一把椅子，你会先改什么？", "如果少的是杯子，办法还一样吗？"],
    evidenceTargets: ["进入假设", "比较解决办法", "把办法迁移到明天"],
    wrapUpQuestion: "你觉得这个问题该临时解决，还是改规则？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "hypothetical-thinking",
    coachFocus: "把“会发生什么”推进到“怎样更好地处理”。",
  },
  {
    id: "whatif-two-moons-1",
    themeId: "what-if",
    title: "如果天上有两个月亮",
    scenarioType: "world-change",
    levelRange: [2, 4],
    targetThinkingMoves: ["predict", "transfer", "reflect"],
    variables: [variable("change", "世界变化", ["两个月亮", "两个太阳"])],
    imagePrompt: "夜空里有两个月亮，城市和树影都更亮，画面梦幻但清楚。",
    sceneSetup: "林老师昨晚做梦时，一抬头，天上居然挂着两个月亮。",
    sceneDetail: "醒来以后林老师还记得那种亮亮的感觉：如果是真的，晚上会不会整个世界都不一样？",
    hook: "林老师昨晚做梦，梦见天上挂着两个月亮。",
    openingQuestion: "要是天上真的有两个月亮，晚上看起来会有什么不一样？",
    scaffoldOptions: ["可能更亮", "影子可能变多", "动物作息可能变"],
    conditionChanges: ["要是你要把这个世界画下来，你最想多画哪一部分？", "如果月亮一个大一个小，变化会不一样吗？"],
    evidenceTargets: ["预测多个变化", "扩展系统影响", "用画面表征想法"],
    wrapUpQuestion: "这个新世界最需要改哪条生活习惯？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "hypothetical-thinking",
    coachFocus: "让孩子练习从一个假设往外扩，形成多个可能变化。",
  },
  {
    id: "whatif-rule-1",
    themeId: "what-if",
    title: "如果教室没有规则",
    scenarioType: "rule-removal",
    levelRange: [3, 4],
    targetThinkingMoves: ["predict", "compare", "reflect"],
    variables: [variable("setting", "场景", ["教室", "游乐场"])],
    imagePrompt: "教室里规则卡片消失，孩子们开始各做各的，画面可讨论但不混乱。",
    sceneSetup: "林老师想象了一下，教室里所有规则突然一下子都消失了。",
    sceneDetail: "林老师忍不住笑了一下，又有点担心：刚开始也许很好玩，可第一个麻烦会是什么呢？",
    hook: "林老师想象了一下一个完全没有规则的教室。",
    openingQuestion: "要是教室里一条规则都没有，你觉得先会发生什么？",
    scaffoldOptions: ["可能很自由", "可能有人听不清", "可能东西不好找"],
    conditionChanges: ["要是只能留下一条规则，你会选哪一条？", "如果是游乐场没有规则，最先麻烦的会一样吗？"],
    evidenceTargets: ["预测规则消失后果", "比较规则重要性", "反思保留规则"],
    wrapUpQuestion: "你留下的那条规则是为了解决什么问题？",
    suggestedInput: "voice",
    goalId: "logical-reasoning",
    subGoalId: "multi-step-reasoning",
    coachFocus: "从“乱不乱”走到“规则是为了解决什么问题”。",
  },
  {
    id: "whatif-book-1",
    themeId: "what-if",
    title: "如果一本书没有字",
    scenarioType: "communication-redesign",
    levelRange: [2, 4],
    targetThinkingMoves: ["represent", "compare", "reflect"],
    variables: [variable("medium", "表达方式", ["图片", "声音"])],
    imagePrompt: "一本没有字的书打开，页面上留白，旁边有图片、声音和符号提示。",
    sceneSetup: "林老师捡到一本厚厚的书，翻开以后每一页都干干净净，没有一个字。",
    sceneDetail: "林老师把书举给你看：可我总觉得它还是想讲一个故事，只是没用平常的方法。",
    hook: "林老师捡到一本神奇的书，翻开来一页字都没有。",
    openingQuestion: "要是一本书没有字，它还能怎么把故事讲给你听？",
    scaffoldOptions: ["用图片讲", "用声音讲", "用符号或颜色提示"],
    conditionChanges: ["要是想让别人也看懂，你会加上什么提示？", "如果没有图片，只剩声音，还能讲清吗？"],
    evidenceTargets: ["提出多种表征", "比较可理解性", "改进表达办法"],
    wrapUpQuestion: "你会给这本书加哪一种提示？为什么？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "divergent-thinking",
    coachFocus: "鼓励孩子提出多种可能，再比较哪一种更容易被别人理解。",
  },
  {
    id: "whatif-rainbow-road-1",
    themeId: "what-if",
    title: "如果道路会变颜色",
    scenarioType: "signal-design",
    levelRange: [3, 4],
    targetThinkingMoves: ["predict", "compare", "reflect"],
    variables: [variable("signal", "提示方式", ["颜色", "声音"])],
    imagePrompt: "城市道路根据情况变成不同颜色，行人和车辆根据颜色调整速度。",
    sceneSetup: "林老师想象城市里的路像心情一样，会自己变颜色。",
    sceneDetail: "林老师一边走一边想：如果脚下的路突然变成别的颜色，人会不会一下子知道该快一点还是慢一点？",
    hook: "林老师想象城市里的路，会像心情一样变颜色。",
    openingQuestion: "要是道路会变颜色，你觉得不同颜色可以提醒大家什么？",
    scaffoldOptions: ["红色提醒停一停", "黄色提醒慢一点", "绿色提醒可以走"],
    conditionChanges: ["要是颜色太多，大家反而看不懂，你会怎么改？", "如果有人看不清颜色，还需要什么提示？"],
    evidenceTargets: ["设计信号含义", "预测误解风险", "改进规则清晰度"],
    wrapUpQuestion: "你会保留几种颜色，为什么？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "hypothetical-thinking",
    coachFocus: "让孩子从想象走到规则设计，看到好想法也需要清楚。",
  },
  {
    id: "whatif-everyone-whisper-1",
    themeId: "what-if",
    title: "如果大家只能小声说话",
    scenarioType: "communication-constraint",
    levelRange: [2, 4],
    targetThinkingMoves: ["predict", "transfer", "reflect"],
    variables: [variable("constraint", "限制", ["只能小声说话", "不能用手指"])],
    imagePrompt: "教室里大家只能小声说话，孩子们用手势、图卡和靠近倾听沟通。",
    sceneSetup: "林老师想象今天教室里突然多了一条新限制：大家只能小声说话。",
    sceneDetail: "她轻轻捂住嘴：那上课、借东西、找朋友，会不会都要换办法？",
    hook: "林老师想试试一个安静版的教室。",
    openingQuestion: "如果大家今天只能小声说话，第一件会变难的事是什么？",
    scaffoldOptions: ["叫远处的人会变难", "借东西要靠近说", "可以用手势帮忙"],
    conditionChanges: ["如果还不能用手势，你会加什么工具？", "要是换成图书馆，这条规则还麻烦吗？"],
    evidenceTargets: ["预测限制影响", "迁移到不同场景", "创造辅助办法"],
    wrapUpQuestion: "你会设计什么安静沟通工具？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "hypothetical-thinking",
    coachFocus: "让孩子在限制中预测连锁影响，并创造替代沟通方式。",
  },
  {
    id: "whatif-time-slow-1",
    themeId: "what-if",
    title: "如果排队时能让时间变慢",
    scenarioType: "consequence-chain",
    levelRange: [3, 4],
    targetThinkingMoves: ["predict", "compare", "reflect"],
    variables: [variable("power", "假设能力", ["让时间变慢", "让队伍变短"])],
    imagePrompt: "游乐场排队时钟变慢，队伍里孩子表情不同，旁边有规则提示牌。",
    sceneSetup: "林老师在游乐场排队时突然想：如果能让排队的时间变慢，会不会更容易等？",
    sceneDetail: "她又马上皱眉：可是时间变慢，别人会不会也被影响？",
    hook: "林老师想到了一个有点厉害、也有点麻烦的能力。",
    openingQuestion: "如果排队时能让时间变慢，第一件好事和第一件麻烦事可能是什么？",
    scaffoldOptions: ["好处是不会错过细节", "麻烦是大家等更久", "也许只让自己感觉变慢"],
    conditionChanges: ["如果只有你感觉时间变慢，还公平吗？", "要是大家都能用这个能力，队伍会怎样？"],
    evidenceTargets: ["预测好处和麻烦", "比较个人和大家", "反思规则边界"],
    wrapUpQuestion: "你会给这个能力加一条什么使用规则？",
    suggestedInput: "voice",
    goalId: "creative-thinking",
    subGoalId: "hypothetical-thinking",
    coachFocus: "把想象推进到后果链和规则边界，避免只停在神奇设定。",
  },
];

export function scenarioTemplateToDailyQuestion(
  template: ScenarioTemplate,
  variantSeed?: string | number,
): DailyQuestion {
  const [minLevel] = template.levelRange;
  const seed = variantSeed === undefined ? undefined : String(variantSeed);
  const selectedVariables = seed
    ? buildScenarioTemplateVariables(template, seed)
    : {};
  const render = (value: string) =>
    applyScenarioTemplateVariablesToText(value, template, selectedVariables);
  const renderList = (values: string[]) =>
    applyScenarioTemplateVariablesToList(values, template, selectedVariables);

  return {
    id: template.id,
    scenarioTemplateId: template.id,
    scenarioVariantKey: seed ? `${template.id}:${hashSeed(`${seed}:${template.id}`)}` : undefined,
    scenarioVariables: seed ? selectedVariables : undefined,
    themeId: template.themeId,
    title: render(template.title),
    progressionStageId: template.progressionStageId,
    adaptationLevel: minLevel,
    sceneSetup: render(template.sceneSetup),
    sceneDetail: render(template.sceneDetail),
    hook: render(template.hook),
    mainQuestion: render(template.openingQuestion),
    firstFollowUp: renderList(template.scaffoldOptions)[0] ?? render(template.openingQuestion),
    twistFollowUp: renderList(template.conditionChanges)[0] ?? render(template.wrapUpQuestion),
    suggestedInput: template.suggestedInput,
    goalId: template.goalId,
    subGoalId: template.subGoalId,
    coachFocus: render(template.coachFocus),
  };
}

export const DAILY_SCENARIO_QUESTION_BANK = DAILY_SCENARIO_TEMPLATES.map(
  scenarioTemplateToDailyQuestion,
);

export const DAILY_SCENARIO_TEMPLATE_MAP = new Map(
  DAILY_SCENARIO_TEMPLATES.map((template) => [template.id, template]),
);

export function getScenarioTemplate(templateId: string | undefined) {
  return templateId ? DAILY_SCENARIO_TEMPLATE_MAP.get(templateId) : undefined;
}

export function getScenarioTemplateForQuestion(question: DailyQuestion | undefined) {
  return question ? getScenarioTemplate(question.scenarioTemplateId ?? question.id) : undefined;
}

export function buildScenarioQuestionVariant(
  question: DailyQuestion,
  variantSeed: string | number | undefined,
) {
  const template = getScenarioTemplateForQuestion(question);
  if (!template || variantSeed === undefined) return question;

  return {
    ...scenarioTemplateToDailyQuestion(template, variantSeed),
    id: question.id,
    adaptationLevel: question.adaptationLevel,
  };
}
