import type { PatternChallengeCard } from "@/types/goals";

export const PATTERN_RECOGNITION_CHALLENGE_BANK: PatternChallengeCard[] = [
  {
    id: "pr-qty-l1-skip3",
    difficultyLevel: "L1",
    patternKind: "quantity",
    stem: "3, 6, 9, __",
    prompt: "看看这排数字，每次是怎么变的？下一个会是什么？",
    options: ["10", "12", "15"],
    answer: "12",
    ruleHint: "每次多3",
    contrastChoice: "10",
    explanationFrame: "它是不是每次都在___，所以后面是___。",
  },
  {
    id: "pr-qty-l1-down2",
    difficultyLevel: "L1",
    patternKind: "quantity",
    stem: "10, 8, 6, __",
    prompt: "这次数字在往哪边变？下一个应该是什么？",
    options: ["4", "5", "7"],
    answer: "4",
    ruleHint: "每次少2",
    contrastChoice: "5",
    explanationFrame: "我发现它每次都___，所以后面应该是___。",
  },
  {
    id: "pr-attr-l1-color-alt",
    difficultyLevel: "L1",
    patternKind: "attribute",
    stem: "红, 黄, 红, 黄, __",
    prompt: "颜色在轮流变化。下一个会轮到谁？",
    options: ["红", "黄", "蓝"],
    answer: "红",
    ruleHint: "红黄重复",
    contrastChoice: "黄",
    explanationFrame: "它是在___重复，所以后面是___。",
  },
  {
    id: "pr-attr-l1-shape-alt",
    difficultyLevel: "L1",
    patternKind: "attribute",
    stem: "圆, 方, 圆, 方, __",
    prompt: "看看形状在怎么排队。下一个是什么？",
    options: ["三角", "圆", "方"],
    answer: "圆",
    ruleHint: "圆方重复",
    contrastChoice: "方",
    explanationFrame: "前面一直是___在重复，所以后面应该是___。",
  },
  {
    id: "pr-space-l1-arrow-alt",
    difficultyLevel: "L1",
    patternKind: "space",
    stem: "↑, →, ↑, →, __",
    prompt: "箭头方向在轮流变。下一个指向哪里？",
    options: ["↑", "→", "↓"],
    answer: "↑",
    ruleHint: "两个方向轮流",
    contrastChoice: "→",
    explanationFrame: "箭头是在___轮流，所以后面会是___。",
  },
  {
    id: "pr-qty-l2-skip4",
    difficultyLevel: "L2",
    patternKind: "quantity",
    stem: "4, 8, 12, __",
    prompt: "这排数字跳得比刚才更大一点。下一个会是什么？",
    options: ["14", "16", "18"],
    answer: "16",
    ruleHint: "每次多4",
    contrastChoice: "14",
    explanationFrame: "它每次都___，所以后面是___。",
  },
  {
    id: "pr-qty-l2-repeat-pairs",
    difficultyLevel: "L2",
    patternKind: "quantity",
    stem: "2, 2, 4, 4, 6, 6, __",
    prompt: "数字不是只看一个一个变，要看成对地排。下一个是什么？",
    options: ["6", "8", "10"],
    answer: "8",
    ruleHint: "两个两个重复，再往上加2",
    contrastChoice: "6",
    explanationFrame: "我看到它是___，所以后面应该是___。",
  },
  {
    id: "pr-attr-l2-size-alt",
    difficultyLevel: "L2",
    patternKind: "attribute",
    stem: "大, 小, 大, 小, __",
    prompt: "大小在轮流出现。下一个会是什么？",
    options: ["大", "中", "小"],
    answer: "大",
    ruleHint: "大小重复",
    contrastChoice: "小",
    explanationFrame: "它是___在重复，所以后面是___。",
  },
  {
    id: "pr-attr-l2-length-alt",
    difficultyLevel: "L2",
    patternKind: "attribute",
    stem: "长, 短, 长, 短, __",
    prompt: "看长度在怎么换。下一个应该是谁？",
    options: ["长", "短", "一样长"],
    answer: "长",
    ruleHint: "长短重复",
    contrastChoice: "短",
    explanationFrame: "前面一直是___轮流，所以后面是___。",
  },
  {
    id: "pr-space-l2-diagonal",
    difficultyLevel: "L2",
    patternKind: "space",
    stem: "↗, ↘, ↗, ↘, __",
    prompt: "方向在斜着来回换。下一个箭头会指哪里？",
    options: ["↙", "↘", "↗"],
    answer: "↗",
    ruleHint: "两个斜方向轮流",
    contrastChoice: "↘",
    explanationFrame: "它是在___和___之间轮流，所以后面是___。",
  },
  {
    id: "pr-qty-l3-step-pairs",
    difficultyLevel: "L3",
    patternKind: "quantity",
    stem: "5, 7, 7, 9, 9, 11, __",
    prompt: "这排数字要看重复和增加一起发生。下一个是什么？",
    options: ["11", "12", "13"],
    answer: "11",
    ruleHint: "每个数先重复一次，再加2",
    contrastChoice: "13",
    explanationFrame: "我发现它是___，所以这一步应该是___。",
  },
  {
    id: "pr-attr-l3-color-shape-block",
    difficultyLevel: "L3",
    patternKind: "attribute",
    stem: "红圆, 红方, 黄圆, 黄方, 红圆, __",
    prompt: "这次不是只看一种变化，要看颜色和形状一起怎么排。空格里是什么？",
    options: ["黄圆", "红方", "黄方"],
    answer: "红方",
    ruleHint: "两个颜色块里各自圆方排列，然后重新开始",
    contrastChoice: "黄圆",
    explanationFrame: "它是按___在循环，所以后面应该是___。",
  },
  {
    id: "pr-space-l3-turning",
    difficultyLevel: "L3",
    patternKind: "space",
    stem: "↑, ←, ↓, →, __",
    prompt: "箭头一直在转。它下一步会转到哪里？",
    options: ["↑", "←", "↓"],
    answer: "↑",
    ruleHint: "每次转90度",
    contrastChoice: "↓",
    explanationFrame: "它每次都在___，所以后面会是___。",
  },
  {
    id: "pr-qty-l4-alternating-jumps",
    difficultyLevel: "L4",
    patternKind: "quantity",
    stem: "6, 9, 13, 16, 20, __",
    prompt: "这次不是一直加同一个数。你能找到两个轮流出现的跳法吗？",
    options: ["22", "23", "24"],
    answer: "23",
    ruleHint: "加3、加4轮流",
    contrastChoice: "24",
    explanationFrame: "我发现它是在___和___之间轮流，所以后面是___。",
  },
  {
    id: "pr-attr-l4-triplet-cycle",
    difficultyLevel: "L4",
    patternKind: "attribute",
    stem: "红圆, 黄方, 蓝三角, 红圆, 黄方, __",
    prompt: "这排图形不是两两轮换，而是三个一组在循环。空格里是什么？",
    options: ["蓝三角", "红方", "黄圆"],
    answer: "蓝三角",
    ruleHint: "三个一组循环",
    contrastChoice: "红方",
    explanationFrame: "它是按___、___、___在循环，所以后面是___。",
  },
  {
    id: "pr-space-l4-turn-circle",
    difficultyLevel: "L4",
    patternKind: "space",
    stem: "↑, →, ↓, ←, ↑, __",
    prompt: "方向一直按固定顺序转圈。下一个箭头会指哪里？",
    options: ["←", "→", "↓"],
    answer: "→",
    ruleHint: "每次转90度",
    contrastChoice: "↓",
    explanationFrame: "它每次都在___，所以后面会是___。",
  },
];
