import type { ActivityTemplate } from "@/types/goals";

const MATH_ACTIVITIES: ActivityTemplate[] = [
  {
    id: "number-pattern-hunt",
    label: "Number Pattern Hunt",
    goalId: "math-thinking",
    subGoalId: "pattern-recognition",
    description: "Spot the changing rule in a short number pattern and predict the next item.",
    suggestedTools: ["narrate", "show_choices", "show_text_input"],
    ageRange: [6, 12],
    durationMinutes: 8,
    systemPromptFragment: "Current activity: pattern recognition. Give one short pattern challenge, ask for the next item, then ask the child to explain the rule in simple language.",
    exampleFlow: 'narrate -> show_choices -> narrate -> show_text_input',
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["answer", "self_explanation", "activity_summary"],
    evaluatorRubricId: "math-pattern-recognition",
    fallbackWhenEvidenceThin: "Switch to a shorter pattern and ask the child to say what changes each step.",
  },
  {
    id: "marble-compare",
    label: "Marble Compare",
    goalId: "math-thinking",
    subGoalId: "quantity-comparison",
    description: "Compare two groups and explain how many more, fewer, or how the amount changes.",
    suggestedTools: ["narrate", "show_choices", "show_text_input"],
    ageRange: [6, 11],
    durationMinutes: 7,
    systemPromptFragment: "Current activity: quantity comparison. Use two small groups, ask who has more or fewer, then ask how the difference changes after one item is added or removed.",
    exampleFlow: 'narrate -> show_choices -> narrate -> show_text_input',
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["answer", "self_explanation", "activity_summary"],
    evaluatorRubricId: "math-quantity-comparison",
    fallbackWhenEvidenceThin: "Keep the numbers small and ask for one complete because-sentence.",
  },
  {
    id: "strategy-nim",
    label: "Take-Stones Strategy",
    goalId: "math-thinking",
    subGoalId: "strategy-planning",
    description: "Predict future moves and choose a safer plan in a short take-away game.",
    suggestedTools: ["narrate", "show_choices", "show_text_input"],
    ageRange: [8, 12],
    durationMinutes: 10,
    systemPromptFragment: "Current activity: strategy planning. Use a short take-away game, ask the child which move to make, then ask what will be left and why that move is safer.",
    exampleFlow: 'narrate -> show_choices -> narrate -> show_text_input',
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["strategy_prediction", "self_explanation", "activity_summary"],
    evaluatorRubricId: "math-strategy-planning",
    fallbackWhenEvidenceThin: "Reduce the board state to one-step prediction before asking for a longer plan.",
  },
  {
    id: "shape-spy",
    label: "Shape Spy",
    goalId: "math-thinking",
    subGoalId: "spatial-reasoning",
    description: "Describe what changes when a shape rotates, flips, or moves.",
    suggestedTools: ["narrate", "show_image", "show_choices", "show_text_input"],
    ageRange: [6, 10],
    durationMinutes: 6,
    systemPromptFragment: "Current activity: spatial reasoning. Show simple shape options, ask which one matches after a turn or flip, then ask how the child noticed it.",
    exampleFlow: 'narrate -> show_image -> show_choices -> show_text_input',
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["answer", "self_explanation", "activity_summary"],
    evaluatorRubricId: "math-spatial-reasoning",
    fallbackWhenEvidenceThin: "Return to one visible transformation and ask the child to point out the moved part.",
  },
  {
    id: "money-counter",
    label: "买东西找钱",
    goalId: "math-thinking",
    subGoalId: "arithmetic-fluency",
    description: "计算总价和找零，在购物场景中练习加减法运算。",
    suggestedTools: ["narrate", "show_choices", "show_text_input"],
    ageRange: [6, 9],
    durationMinutes: 7,
    systemPromptFragment: "Current activity: arithmetic fluency — shopping and change. You are a magical shopkeeper. The child is a customer buying candy. L1: single item priced 1-5 yuan, pay with 5 or 10 yuan, ask how much change. L2: buy 2-3 items totaling 10-20 yuan, pay with 20 yuan. L3: multiple items, possibly returning one mid-transaction. Always ask the child to explain why the change amount is what it is, not just the number.",
    exampleFlow: "narrate -> show_choices -> narrate -> show_text_input",
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["answer", "self_explanation", "activity_summary"],
    evaluatorRubricId: "math-arithmetic-fluency",
    fallbackWhenEvidenceThin: "Show a simpler scenario: one item costs 3 yuan, pay with 5 yuan, how much change?",
  },
  {
    id: "number-split",
    label: "数字拆分家",
    goalId: "math-thinking",
    subGoalId: "number-composition",
    description: "将一个数拆分为两个或三个正整数之和，训练数字组合感觉。",
    suggestedTools: ["narrate", "show_choices", "show_text_input"],
    ageRange: [5, 8],
    durationMinutes: 6,
    systemPromptFragment: "Current activity: number composition — number splitting. Play 'number splitting house': given a target number, ask the child 'can you split this into two (or three) numbers that add up to it?' L1: target 5-8, split into 2 positive integers, encourage listing all possibilities. L2: target 10-15, at least 2 distinct ways. L3: target 10-20, split into 3 positive integers. Ask: why did you try that combination first?",
    exampleFlow: "narrate -> show_text_input -> narrate -> show_choices",
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["answer", "self_explanation", "activity_summary"],
    evaluatorRubricId: "math-number-composition",
    fallbackWhenEvidenceThin: "Use physical props: show 7 objects, ask 'can you put some here and some here to make 7?'",
  },
  {
    id: "magic-equation",
    label: "魔法等式",
    goalId: "math-thinking",
    subGoalId: "equation-thinking",
    description: "在缺失数字的等式中找出未知数，培养等号两边相等的代数直觉。",
    suggestedTools: ["narrate", "show_text_input", "show_choices"],
    ageRange: [6, 10],
    durationMinutes: 7,
    systemPromptFragment: "Current activity: equation thinking — the magic box. You are a magician; the missing number is hidden in a magic box. L1: □ + a = b, solve for □ directly. L2: a + □ = b or a - □ = c, requires reverse operation. L3: □ + □ = b (multiple solutions). Always ask: 'how do you know it must be this number?' to build the intuition that both sides of the equals sign must be equal.",
    exampleFlow: "narrate -> show_text_input -> narrate -> show_choices",
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["answer", "self_explanation", "activity_summary"],
    evaluatorRubricId: "math-equation-thinking",
    fallbackWhenEvidenceThin: "Go back to a concrete scenario: 'you have some apples, I give you 3 more, now you have 7. How many did you start with?'",
  },
];

const LOGIC_ACTIVITIES: ActivityTemplate[] = [
  {
    id: "who-is-lying",
    label: "Who Is Lying",
    goalId: "logical-reasoning",
    subGoalId: "elimination-method",
    description: "Use elimination to identify the option that cannot be true.",
    suggestedTools: ["narrate", "show_choices", "show_text_input"],
    ageRange: [7, 12],
    durationMinutes: 8,
    systemPromptFragment: "Current activity: elimination method. Present three or four clues, let the child choose the option that remains, then ask which option was ruled out first and why.",
    exampleFlow: 'narrate -> show_choices -> narrate -> show_text_input',
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["answer", "self_explanation", "activity_summary"],
    evaluatorRubricId: "logic-elimination",
    fallbackWhenEvidenceThin: "Reduce the options and ask the child to eliminate just one before answering.",
  },
  {
    id: "if-then-chain",
    label: "If-Then Chain",
    goalId: "logical-reasoning",
    subGoalId: "conditional-thinking",
    description: "Follow one or two linked conditions to reach the correct conclusion.",
    suggestedTools: ["narrate", "show_choices", "show_text_input"],
    ageRange: [8, 12],
    durationMinutes: 7,
    systemPromptFragment: "Current activity: conditional thinking. Present one or two linked if-then clues, ask for the conclusion, then ask which clue mattered first.",
    exampleFlow: 'narrate -> show_choices -> narrate -> show_text_input',
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["answer", "self_explanation", "activity_summary"],
    evaluatorRubricId: "logic-conditional",
    fallbackWhenEvidenceThin: "Return to a single if-then clue and ask for a complete because-sentence.",
  },
  {
    id: "logic-ladder",
    label: "Logic Ladder",
    goalId: "logical-reasoning",
    subGoalId: "multi-step-reasoning",
    description: "Break a problem into two or three linked reasoning steps.",
    suggestedTools: ["narrate", "show_choices", "show_text_input"],
    ageRange: [8, 12],
    durationMinutes: 8,
    systemPromptFragment: "Current activity: multi-step reasoning. Ask the child for the first step, then the next step, then the final answer, and require a short explanation of the chain.",
    exampleFlow: 'narrate -> show_text_input -> narrate -> show_choices -> show_text_input',
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["answer", "self_explanation", "activity_summary"],
    evaluatorRubricId: "logic-multi-step",
    fallbackWhenEvidenceThin: "Freeze the puzzle after the first step and ask only what changes next.",
  },
];

const CREATIVE_ACTIVITIES: ActivityTemplate[] = [
  {
    id: "rule-inventor",
    label: "Rule Inventor",
    goalId: "creative-thinking",
    subGoalId: "rule-creation",
    description: "Create a new rule for a familiar game and explain how it changes the play.",
    suggestedTools: ["narrate", "show_text_input", "show_choices"],
    ageRange: [7, 12],
    durationMinutes: 8,
    systemPromptFragment: "Current activity: rule creation. Start with a familiar mini-game, ask the child to invent one new rule, then ask whether it feels fair and how to improve it.",
    exampleFlow: 'narrate -> show_text_input -> narrate -> show_choices',
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["answer", "idea_improvement", "activity_summary"],
    evaluatorRubricId: "creative-rule-creation",
    fallbackWhenEvidenceThin: "Offer two possible rule tweaks and ask which one is more fun or fair.",
  },
  {
    id: "many-ways-there",
    label: "Many Ways There",
    goalId: "creative-thinking",
    subGoalId: "divergent-thinking",
    description: "Generate multiple different ideas, then choose one to improve.",
    suggestedTools: ["narrate", "show_text_input", "show_choices"],
    ageRange: [6, 12],
    durationMinutes: 7,
    systemPromptFragment: "Current activity: divergent thinking. Ask for several different ideas, compare two of them, then ask the child to make one idea more interesting or useful.",
    exampleFlow: 'narrate -> show_text_input -> narrate -> show_choices -> show_text_input',
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["answer", "idea_improvement", "activity_summary"],
    evaluatorRubricId: "creative-divergent",
    fallbackWhenEvidenceThin: "Ask for just one more very different idea before judging quality.",
  },
  {
    id: "what-if-world",
    label: "What-If World",
    goalId: "creative-thinking",
    subGoalId: "hypothetical-thinking",
    description: "Explore consequences in an imagined world and refine the idea.",
    suggestedTools: ["narrate", "show_choices", "show_text_input"],
    ageRange: [6, 12],
    durationMinutes: 7,
    systemPromptFragment: "Current activity: hypothetical thinking. Present a simple what-if world, ask what happens next, then ask how the idea could become more believable or interesting.",
    exampleFlow: 'narrate -> show_choices -> show_text_input -> narrate',
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["answer", "idea_improvement", "activity_summary"],
    evaluatorRubricId: "creative-hypothetical",
    fallbackWhenEvidenceThin: "Keep the imagined change small and ask for one clear consequence.",
  },
];

const LANGUAGE_ACTIVITIES: ActivityTemplate[] = [
  {
    id: "explain-it",
    label: "Explain It",
    goalId: "language-thinking",
    subGoalId: "explain-reasoning",
    description: "Explain why an answer makes sense using complete sentences.",
    suggestedTools: ["narrate", "show_choices", "show_text_input", "request_voice"],
    ageRange: [6, 12],
    durationMinutes: 6,
    systemPromptFragment: "Current activity: explain reasoning. Give a short choice question, then require the child to explain the reason in a full sentence using because.",
    exampleFlow: 'narrate -> show_choices -> request_voice -> narrate',
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["answer", "self_explanation", "describe_observation"],
    evaluatorRubricId: "language-explain-reasoning",
    fallbackWhenEvidenceThin: "Use a sentence frame and ask the child to finish it.",
  },
  {
    id: "describe-the-scene",
    label: "Describe the Scene",
    goalId: "language-thinking",
    subGoalId: "describe-observation",
    description: "Describe what is visible before jumping to the conclusion.",
    suggestedTools: ["narrate", "show_image", "show_text_input", "request_voice"],
    ageRange: [6, 12],
    durationMinutes: 6,
    systemPromptFragment: "Current activity: describe observation. Show a simple scene or image, ask what the child notices first, then ask for one more detail and a clear comparison.",
    exampleFlow: 'narrate -> show_image -> request_voice -> narrate',
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["answer", "self_explanation", "describe_observation"],
    evaluatorRubricId: "language-describe-observation",
    fallbackWhenEvidenceThin: "Reduce the scene to two visible details and ask for one complete sentence.",
  },
  {
    id: "opposite-bounce",
    label: "反义词弹弹球",
    goalId: "language-thinking",
    subGoalId: "vocabulary-expansion",
    description: "在蹦蹦跳跳的节奏中学习和使用反义词，扩展词汇量。",
    suggestedTools: ["narrate", "show_choices", "show_text_input"],
    ageRange: [5, 9],
    durationMinutes: 5,
    systemPromptFragment: "Current activity: vocabulary expansion — opposites. You are a bouncy ball that bounces between opposites. Say a word, the child says the opposite. L1: simple adjectives (大/小, 高/低, 上/下). L2: verbs and state words (前进/后退, 开心/难过, 开/关). L3: abstract words (勇敢/胆小, 慷慨/吝啬). After each pair, ask: 'Can you use one of these words in a sentence?'",
    exampleFlow: "narrate -> show_choices -> narrate -> show_text_input",
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["answer", "self_explanation", "describe_observation"],
    evaluatorRubricId: "language-vocabulary-expansion",
    fallbackWhenEvidenceThin: "Use concrete props: show a tall tower and a short tower, ask 'what is the opposite of tall?'",
  },
  {
    id: "picture-story",
    label: "看图说故事",
    goalId: "language-thinking",
    subGoalId: "narrative-thinking",
    description: "观察一幅图片，描述场景并创编一个小故事。",
    suggestedTools: ["narrate", "show_image", "show_text_input", "request_voice"],
    ageRange: [5, 10],
    durationMinutes: 6,
    systemPromptFragment: "Current activity: narrative thinking — picture storytelling. Show a simple, interesting image. Ask the child to describe what they see first (who, what, where), then ask what happened just before this moment, and what might happen next. Encourage one full sentence per answer.",
    exampleFlow: "narrate -> show_image -> request_voice -> narrate -> show_text_input",
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["describe_observation", "idea_improvement", "activity_summary"],
    evaluatorRubricId: "language-narrative",
    fallbackWhenEvidenceThin: "Reduce to three questions: 'Who is in the picture? What are they doing? How do they feel?'",
  },
];

const STRATEGY_ACTIVITIES: ActivityTemplate[] = [
  {
    id: "predict-the-move",
    label: "Predict the Move",
    goalId: "strategy-thinking",
    subGoalId: "opponent-modeling",
    description: "Predict what the other side is likely to do and plan a response.",
    suggestedTools: ["narrate", "show_choices", "show_text_input"],
    ageRange: [8, 12],
    durationMinutes: 8,
    systemPromptFragment: "Current activity: opponent modeling. Describe a short game state, ask what the opponent may do next, then ask how the child should respond and why.",
    exampleFlow: 'narrate -> show_choices -> narrate -> show_text_input',
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["strategy_prediction", "self_explanation", "activity_summary"],
    evaluatorRubricId: "strategy-opponent-modeling",
    fallbackWhenEvidenceThin: "Keep only one opponent move option and ask why it is likely.",
  },
  {
    id: "best-move-lab",
    label: "Best Move Lab",
    goalId: "strategy-thinking",
    subGoalId: "optimal-strategy",
    description: "Compare two plans and justify which one works best.",
    suggestedTools: ["narrate", "show_choices", "show_text_input"],
    ageRange: [8, 12],
    durationMinutes: 8,
    systemPromptFragment: "Current activity: optimal strategy. Present two candidate plans, ask which is strongest, then ask why the weaker plan fails.",
    exampleFlow: 'narrate -> show_choices -> narrate -> show_text_input',
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["strategy_prediction", "self_explanation", "activity_summary"],
    evaluatorRubricId: "strategy-optimal",
    fallbackWhenEvidenceThin: "Shrink the board state and compare only two simple plans.",
  },
  {
    id: "safe-or-risky",
    label: "Safe or Risky",
    goalId: "strategy-thinking",
    subGoalId: "risk-assessment",
    description: "Judge safer and riskier options and explain the tradeoff.",
    suggestedTools: ["narrate", "show_choices", "show_text_input"],
    ageRange: [8, 12],
    durationMinutes: 7,
    systemPromptFragment: "Current activity: risk assessment. Offer a safe option and a risky option, ask which to choose, then ask what could go wrong with the risky plan.",
    exampleFlow: 'narrate -> show_choices -> narrate -> show_text_input',
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["strategy_prediction", "self_explanation", "activity_summary"],
    evaluatorRubricId: "strategy-risk",
    fallbackWhenEvidenceThin: "Start with a more obvious safe-versus-risky pair.",
  },
  {
    id: "tic-tac-think",
    label: "井字棋大师",
    goalId: "strategy-thinking",
    subGoalId: "game-tree-planning",
    description: "在井字棋游戏中思考几步之后的走法，训练前瞻思维。",
    suggestedTools: ["narrate", "show_choices", "show_text_input"],
    ageRange: [6, 11],
    durationMinutes: 8,
    systemPromptFragment: "Current activity: game-tree planning — Tic-Tac-Toe. Play a simplified Tic-Tac-Toe. L1: ask 'which corner should you start with and why?' L2: after opponent's move, ask 'what is your best reply and what does it stop?' L3: ask 'if you go here, what could the opponent do, and what would you do next?' Always ask for a reason, not just the move.",
    exampleFlow: "narrate -> show_choices -> narrate -> show_text_input",
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["strategy_prediction", "self_explanation", "activity_summary"],
    evaluatorRubricId: "strategy-game-tree",
    fallbackWhenEvidenceThin: "Show a board with only two marks and ask: 'where do you put your X to block the opponent?'",
  },
];

const OBSERVATION_ACTIVITIES: ActivityTemplate[] = [
  {
    id: "detail-detective",
    label: "Detail Detective",
    goalId: "observation-induction",
    subGoalId: "systematic-observation",
    description: "Scan a scene methodically and name easy-to-miss details.",
    suggestedTools: ["narrate", "show_image", "show_text_input", "request_voice"],
    ageRange: [6, 12],
    durationMinutes: 7,
    systemPromptFragment: "Current activity: systematic observation. Ask the child to scan an image in order, name what they notice, then ask which detail was easy to miss.",
    exampleFlow: 'narrate -> show_image -> request_voice -> narrate',
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["describe_observation", "self_explanation", "activity_summary"],
    evaluatorRubricId: "observation-systematic",
    fallbackWhenEvidenceThin: "Crop the scene to fewer details and ask the child to scan left to right.",
  },
  {
    id: "spot-the-rule",
    label: "Spot the Rule",
    goalId: "observation-induction",
    subGoalId: "inductive-generalization",
    description: "Find the common rule across several examples and test it.",
    suggestedTools: ["narrate", "show_image", "show_text_input", "show_choices"],
    ageRange: [6, 12],
    durationMinutes: 8,
    systemPromptFragment: "Current activity: inductive generalization. Present several examples, ask for the common rule, then ask whether a new example fits or breaks the rule.",
    exampleFlow: 'narrate -> show_image -> show_text_input -> show_choices',
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["describe_observation", "self_explanation", "transfer_check"],
    evaluatorRubricId: "observation-inductive",
    fallbackWhenEvidenceThin: "Ask the child to group examples before naming the full rule.",
  },
  {
    id: "same-shape-new-world",
    label: "Same Shape New World",
    goalId: "observation-induction",
    subGoalId: "analogy-transfer",
    description: "Transfer a known pattern or structure into a new context.",
    suggestedTools: ["narrate", "show_choices", "show_text_input"],
    ageRange: [7, 12],
    durationMinutes: 8,
    systemPromptFragment: "Current activity: analogy transfer. Remind the child of a known rule, present a new surface story, and ask what stays the same and what changes.",
    exampleFlow: 'narrate -> show_choices -> show_text_input -> narrate',
    coreOrTransfer: "transfer",
    requiredEvidenceSlots: ["describe_observation", "self_explanation", "transfer_check"],
    evaluatorRubricId: "observation-analogy-transfer",
    fallbackWhenEvidenceThin: "Use a more obvious same-structure example before asking for a broader analogy.",
  },
  {
    id: "category-sort",
    label: "分类大王",
    goalId: "observation-induction",
    subGoalId: "categorization",
    description: "将一组物品按共同特征分类，并说明分类依据。",
    suggestedTools: ["narrate", "show_choices", "show_text_input"],
    ageRange: [5, 9],
    durationMinutes: 6,
    systemPromptFragment: "Current activity: categorization. Show a group of 6-8 items (real or illustrated). Ask the child to sort them into groups and tell you why each group belongs together. Then ask: 'Is there another way to sort them? Which grouping feels more useful?' Encourage full-sentence reasoning.",
    exampleFlow: "narrate -> show_choices -> narrate -> show_text_input",
    coreOrTransfer: "core",
    requiredEvidenceSlots: ["describe_observation", "self_explanation", "activity_summary"],
    evaluatorRubricId: "observation-categorization",
    fallbackWhenEvidenceThin: "Reduce to 4 items with only one clear grouping, then ask what the group name is.",
  },
];

export const ALL_ACTIVITIES: ActivityTemplate[] = [
  ...MATH_ACTIVITIES,
  ...LOGIC_ACTIVITIES,
  ...CREATIVE_ACTIVITIES,
  ...LANGUAGE_ACTIVITIES,
  ...STRATEGY_ACTIVITIES,
  ...OBSERVATION_ACTIVITIES,
];

export const ACTIVITY_MAP = new Map<string, ActivityTemplate>(
  ALL_ACTIVITIES.map((activity) => [activity.id, activity]),
);

export function getActivitiesForGoal(goalId: string): ActivityTemplate[] {
  return ALL_ACTIVITIES.filter((activity) => activity.goalId === goalId);
}

export function getActivity(id: string): ActivityTemplate | undefined {
  return ACTIVITY_MAP.get(id);
}
